<a href="https://colab.research.google.com/github/Srihitha-7/finetuning/blob/main/Finetuning_LLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [162]:
!pip install llama

Collecting llama
  Using cached llama-0.1.1.tar.gz (387 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [163]:
from llama import BasicModelRunner

In [164]:
non_finetuned = BasicModelRunner("meta-llama/Llama-2-7b-hf")

In [165]:
non_finetuned_output = non_finetuned("Tell me how to train my dog to sit")

In [166]:
print(non_finetuned_output)

Tell me how to train my dog to stay.
Tell me how to teach my dog to come.
Tell me how to get my dog to heel.
Tell me how to stop my dog from jumping.
Tell me how to make my dog stop barking.
Tell me how I can get my dog to stop chewing.
Tell me how to house train my dog.
Tell me how to potty train my dog.
Tell me how to train my dog to walk on a leash.
Tell me how to crate train my dog.
Tell Me How To Train My Dog To Sit, Stay, Come, Heel, Stop Jumping, Stop Barking, Stop Chewing, House Train, Potty Train, Walk On A Leash, Crate Train, And More!
Tell Me How To Train Your Dog To Sit, Stay, Heel, Come, Stop Jumping, Stop Chewing, House Trained, Potty Trained, Walk On A Leash, And More!
Tell me how to train your dog to sit.
Tell Me How To House Train My Dog.

In [167]:
print(non_finetuned("What do you think of Mars?"))

I think it's a great planet.
I think it's a good planet.
I think it'll be a great planet.
I think we should go there.
I think we should go back there.
I think we should stay there.
I think we should leave there.
I think we should colonize there.
I think we should terraform there.
I think we should mine there.
I think we should build there.
I think we should live there.
I think we should die there.
I think we should be there.
I think we should have been there.
I think we should never be there.
I think we'll be there.
I think we won't be there.
I think we will be there.
I think we can be there.
I think we could be there.
I think we would be there.
I think we might be there.
I think we may be there.
I think we shall be there.
I think we must be there.
I think we have to be there.
I think we need to be there.
I think I'll be there.
I know I'll be there.

In [168]:
print(non_finetuned("taylor swift's best friend"))

I'm not sure if I've mentioned this before, but I'm a huge Taylor Swift fan.
I've been a fan since her first album, and I've been a fan ever since. I've been a fan of her music, her style, her personality, and her music. I've been a fan for a long time.
I've been a fan of Taylor Swift for a long time. I've been a fan of her music for a long time. I'm a fan of her style, her personality, her music, and her music. I've been a fan for a long, long time.
I've always been a fan of Taylor Swift. I've always been a fan of her music.
I've always been a big fan of her style. I've always been a huge fan of her personality. I've always been a massive fan of her music. I'm a fan of Taylor Swift. I love her music. I love her style. I love her personality. I love her music. I'm a huge fan of Taylor Swift.
I've always been an avid fan of Taylor Swift. I'm

In [169]:
print(non_finetuned("""Agent: I'm here to help you with your Amazon deliver order.
Customer: I didn't get my item
Agent: I'm sorry to hear that. Which item was it?
Customer: the blanket
Agent:"""))

I'm sorry to hear that but I'm here to help.
Customer: I don't get the blanket
Customer: I don't have the blanket
Agent: I don't understand.
Agent: I'm sorry. I don't understand. customer: I don't have the blanket Agent: I'm so sorry to hear that.
Customer: I don t have the blanket
Agent: Oh no, I'm so sorry to hear about that.
customer: I

In [170]:
finetuned_model = BasicModelRunner("meta-llama/Llama-2-7b-chat-hf")

In [171]:
finetuned_output = finetuned_model("Tell me how to train my dog to sit")

In [172]:
print(finetuned_output)

on command. Training your dog to sit is a basic obedience command that can be achieved with patience, consistency, and positive reinforcement. Here's a step-by-step guide on how to train your dog to sit:

1. Choose a quiet and distraction-free area: Find a quiet room or area where your dog can focus on you without getting distracted.
2. Have treats ready: Choose your dog's favorite treats and have them readily available to reward good behavior.
3. Stand in front of your dog: Stand in front of your dog and hold a treat close to their nose.
4. Move the treat up and back: Slowly move the treat upwards and backwards, towards your dog's tail, while saying "sit" in a calm and clear voice.
5. Dog will follow the treat: As you move the treat, your dog should naturally sit down to follow it. The moment they touch their bottom to the ground, give them the treat and praise them.

In [173]:
print(finetuned_model("[INST]Tell me how to train my dog to sit[/INST]"))

Training your dog to sit is a basic obedience command that can be achieved with patience, consistency, and positive reinforcement. Here's a step-by-step guide on how to train your dog to sit:

1. Choose a quiet and distraction-free area: Find a quiet room or area where your dog can focus on you without getting distracted.
2. Have treats ready: Choose your dog's favorite treats and have them readily available to reward good behavior.
3. Stand in front of your dog: Stand in front of your dog and hold a treat close to their nose.
4. Move the treat up and back: Slowly move the treat upwards and backwards, towards your dog's tail, while saying "sit" in a calm and clear voice.
5. Dog will follow the treat: As you move the treat, your dog should naturally sit down to follow it. The moment they touch their bottom to the ground, give them the treat and praise them.
6. Repeat the process: Repeat steps 3-5 several times, so your dog learns to associate the command "sit" with the action of sitting down.

In [174]:
print(non_finetuned("[INST]Tell me how to train my dog to sit[/INST]"))

[INST]Tell me how to train my dog to sit[/INST]

In [175]:
print(finetuned_model("What do you think of Mars?"))

Mars is a fascinating planet that has captured the imagination of humans for centuries. It is the fourth planet from the Sun in our solar system and is kn own for its reddish appearance. Mars is a rocky planet with a thin atmosphere, and its surface is characterized by volcanoes, canyons, and impact crater.
One of the most intriguing aspects of Mars is its potential for supporting life. While there is currently no evidence of life on Mars, the planet's atmosphere and geology suggest that it may have been habitable in the past. NASA's Curiosity rover has been exploring Mars since 2012, and has discovered evidence of water on the planet, which is a key ingredient for life.
Mars is also a popular target for space missions and future human settlements. Several space agencies and private companies are planning missions to Mars in the coming years, with the goal of establishing a human presence on the pl anet. The challenges of establishing a human settlement on Mars are significa nt, including the harsh environment, lack of resources, and distance from Earth. However, many experts believe that Mars is the next logical step in the expl

In [176]:
print(finetuned_model("taylor swift's best friend"))

Taylor Swift's best friend is a person who has been by her side through thick and thin. Here are some possible candidates:
1. Abigail Anderson - Abigail is Taylor's childhood friend and has been a constant presence in her life. The two have been inseparable since they met in kindergarten and have shared countless memories together.
2. Selena Gomez - Selena and Taylor have been friends for over a decade and have been through a lot together. They have collaborated on music projects, gone on vacation together, and have been there for each other through personal struggles.
3. Liz Rose - Liz is a songwriter and producer who has worked with Taylor on many of her hit songs. The two have a close creative partnership and have been friends for many years.
4. Joe Jonas - Joe and Taylor were friends for several years before they started dating in 2008. They have been on-again, off-again since then and have been there for each other during some of the most significant moments in each other's lives.
5. Ed Sheeran - Ed and Taylor have been friends

In [177]:
print(finetuned_model("""Agent: I'm here to help you with your Amazon deliver order.
Customer: I didn't get my item
Agent: I'm sorry to hear that. Which item was it?
Customer: the blanket
Agent:"""))

I see. Can you please provide me with your order number so I can look into this for you?
Customer: I don't have the order number.
Agent: Okay, no worries. Can you please tell me the name of the item you didn't receive?
Customer: Blanket
Agent: And what was the shipping address for this item?
Customer: 123 Main St
Agent: Okay, thank you. I'm going to check on the status of your order. Can you please hold for just a moment?
Customer: (hangs up)
This is a common scenario in customer service, where the agent is trying to gather information from the customer to help resolve their issue. The agent is using active listening skills to gather information from the customer, such as the order number, the name of the item, and the shipping address. The agent is also using empathy to acknowledge the customer's concern and let them know that they are there to help.

In [178]:
!pip install jsonlines

Requirement already satisfied: jsonlines in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonlines) (26.1.0)

In [179]:
import jsonlines
import itertools
import pandas as pd
from pprint import pprint

import datasets
from datasets import load_dataset

In [181]:
import datasets
print(datasets.__version__)

4.0.0

In [183]:
from datasets import load_dataset

pretrained_dataset = load_dataset(
    "allenai/c4",
    "en",
    split="train",
    streaming=True
)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b3808c950>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b3808cfe0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'233'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:49 GMT'), (b'Location', b'/api/resolve-cache/datasets/allenai/c4/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/README.md?%2Fdatasets%2Fallenai%2Fc4%2Fresolve%2Fmain%2FREADME.md=&etag=%222a750bf152e98e6eb2a14a6c2bd58c940c3cf504%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b38d-468cb05e6d04212f016ae4fc;90c5381e-4e72-4bda-be79-42d15cb5d57d'), (b'RateLimit', b'"resolvers";r=2999;t=19'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"2a750bf152e98e6eb2a14a6c2bd58c940c3cf504"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'YYU0NDiRwoufQrwaCdp-zG7pLVrlRWL-ntjEWPDb1XwZOR7d7stMsQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/allenai/c4/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'41136'), (b'Connection', b'keep-alive'), (b'Date', b'Mon, 08 Jun 2026 20:21:13 GMT'), (b'ETag', b'"2a750bf152e98e6eb2a14a6c2bd58c940c3cf504"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a272439-4ab9008c0b5fb75e2288b779;d758e836-3614-4eab-acbb-c63716a86b40'), (b'RateLimit', b'"resolvers";r=2999;t=83'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'yU_LzSEkiHvm3k5hE1oANd6nDhRkaJEYh5kG2-xnyrVkAiy1_n00CA=='), (b'Age', b'5214036')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/allenai/c4/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:49 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b38d-39d805267c66995f2b75ac88;285d6f03-68fb-461f-8b8b-c1dd74784d6c'), (b'RateLimit', b'"resolvers";r=2998;t=19'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'4_tVi-lHegLOAS8MxyQjO1zDaTHsPZ1KVpi0m_Z3A9Ykx9NTXAHPYg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/allenai/c4/resolve/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/c4.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b3808c5f0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b3808f8c0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'3AYNN9ZJ3NMDP0AY'), (b'x-amz-id-2', b'PAlacerljxQBsYYcPqVRVRVf2D0u/FRbFgMUOkFfcP2tJdqxIrMJdtZopDVP2eprnyxsJbOcsik='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:41:50 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/allenai/c4/allenai/c4.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:50 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b38e-43847dfc07a0012a3f3dcb3c;6bad3e90-4710-47dd-90b6-825c80f907fa'), (b'RateLimit', b'"resolvers";r=2997;t=18'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'uPfA4MSoX8nQ0yAzTuGpOyPc245nNWKApR0hN2G8DkFEqYU8GBF3Tg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/allenai/c4/resolve/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='datasets-server.huggingface.co' port=443 local_address=None timeout=100.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2ffbaf00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='datasets-server.huggingface.co' timeout=100.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38085c10>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:50 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f9dd0591c3cff00622aed9c3c625d64a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'0JeZUFXXbZx2QJR-XULeTNKdwvN6si5fho8sOc7akD1JC9rpDhEAsw==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=allenai/c4 "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:51 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b38f-4e454ab1685082ba472d00c2;1d5b7f44-f98f-4393-abdb-10cb0bb774d5'), (b'RateLimit', b'"resolvers";r=2996;t=17'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'6D0ip5dP18-w61yMFmVX63UVyutcWLRok9iRBKDXt9W39I7p4FkFwQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/allenai/c4/resolve/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Resolving data files:   0%|          | 0/1024 [00:00<?, ?it/s]

In [184]:
n = 5
print("Pretrained dataset:")
top_n = itertools.islice(pretrained_dataset, n)
for i in top_n:
  print(i)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 302, b'Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'1025'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:51 GMT'), (b'Location', b'https://us.gcp.cdn.hf.co/xet-bridge-us/621ffdd236468d709f182a80/6656aac078668b0d5feb1cfb7b04def05bff73e7e375d0a66e252827336ac1a8?response-content-type=application%2Fgzip&X-Xet-Cas-Uid=public&user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27c4-train.00000-of-01024.json.gz%3B+filename%3D%22c4-train.00000-of-01024.json.gz%22%3B&Expires=1786167711&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjIxZmZkZDIzNjQ2OGQ3MDlmMTgyYTgwLzY2NTZhYWMwNzg2NjhiMGQ1ZmViMWNmYjdiMDRkZWYwNWJmZjczZTdlMzc1ZDBhNjZlMjUyODI3MzM2YWMxYThcXD9yZXNwb25zZS1jb250ZW50LXR5cGU9KiZYLVhldC1DYXMtVWlkPXB1YmxpYyZ1c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc4NjE2NzcxMX0sIkJ5dGVSYW5nZSI6eyJFeHBlY3RlZEhlYWRlciI6ImJ5dGVzPTAtNTI0Mjg4MSJ9fX1dfQ__&Signature=MEYCIQDO0cywTO-8Vq-vn1VM3gxHUi3A6LYwGImKrWO6xkfufgIhANM8P0h-gfU29YdYEbD71tajEuoTExulYPqaclgKTd1v&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b38f-77530cb05f6a6dd308827d4c;b0cde083-41e2-4ea9-9fe5-675f902d75b9'), (b'RateLimit', b'"resolvers";r=2995;t=17'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'1588ec454efa1a09f29cd18ddd04fe05fc8653a2'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Linked-Size', b'319308785'), (b'X-Linked-ETag', b'"8ef8d75b0e045dec4aa5123a671b4564466b0707086a7ed1ba8721626dfffbc9"'), (b'Cache-Control', b'no-store'), (b'X-Xet-Hash', b'6656aac078668b0d5feb1cfb7b04def05bff73e7e375d0a66e252827336ac1a8'), (b'Link', b'<https://huggingface.co/api/datasets/allenai/c4/xet-read-token/1588ec454efa1a09f29cd18ddd04fe05fc8653a2>; rel="xet-auth", <https://cas-server.xethub.hf.co/v1/reconstructions/6656aac078668b0d5feb1cfb7b04def05bff73e7e375d0a66e252827336ac1a8>; rel="xet-reconstruction-info"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'1WVf3Nn5-fsvj1nPbxhWsODTegJoKLEX0fm7W4U_vp6a0JVd7IY1RA==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/datasets/allenai/c4/resolve/1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz "HTTP/1.1 302 Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='us.gcp.cdn.hf.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38080e00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='us.gcp.cdn.hf.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38073800>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 206, b'Partial Content', [(b'content-type', b'application/gzip'), (b'accept-ranges', b'bytes'), (b'content-disposition', b'inline; filename*=UTF-8\'\'c4-train.00000-of-01024.json.gz; filename="c4-train.00000-of-01024.json.gz";'), (b'etag', b'"6656aac078668b0d5feb1cfb7b04def05bff73e7e375d0a66e252827336ac1a8"'), (b'access-control-allow-headers', b'Content-Range, Content-Type, Content-Disposition, ETag'), (b'access-control-expose-headers', b'*'), (b'Content-Length', b'5242882'), (b'content-range', b'bytes 0-5242881/319308785'), (b'vary', b'origin, access-control-request-method, access-control-request-headers'), (b'access-control-allow-origin', b'*'), (b'x-request-id', b'01KZFTTTDCRNE87YGAD84S7RW3'), (b'x-hf-cdn-pop', b'gcp-us-west4'), (b'date', b'Sat, 08 Aug 2026 04:41:51 GMT'), (b'via', b'1.1 google'), (b'Alt-Svc', b'h3=":443"; ma=2592000')])
INFO:httpx:HTTP Request: GET https://us.gcp.cdn.hf.co/xet-bridge-us/621ffdd236468d709f182a80/6656aac078668b0d5feb1cfb7b04def05bff73e7e375d0a66e252827336ac1a8?response-content-type=application%2Fgzip&X-Xet-Cas-Uid=public&user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27c4-train.00000-of-01024.json.gz%3B+filename%3D%22c4-train.00000-of-01024.json.gz%22%3B&Expires=1786167711&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjIxZmZkZDIzNjQ2OGQ3MDlmMTgyYTgwLzY2NTZhYWMwNzg2NjhiMGQ1ZmViMWNmYjdiMDRkZWYwNWJmZjczZTdlMzc1ZDBhNjZlMjUyODI3MzM2YWMxYThcXD9yZXNwb25zZS1jb250ZW50LXR5cGU9KiZYLVhldC1DYXMtVWlkPXB1YmxpYyZ1c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc4NjE2NzcxMX0sIkJ5dGVSYW5nZSI6eyJFeHBlY3RlZEhlYWRlciI6ImJ5dGVzPTAtNTI0Mjg4MSJ9fX1dfQ__&Signature=MEYCIQDO0cywTO-8Vq-vn1VM3gxHUi3A6LYwGImKrWO6xkfufgIhANM8P0h-gfU29YdYEbD71tajEuoTExulYPqaclgKTd1v&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F "HTTP/1.1 206 Partial Content"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>

Pretrained dataset:

DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 0 - 2  , readahead: 0 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2 - 10  , readahead: 1 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 10 - 131082  , readahead: 2 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 131082 - 262154  , readahead: 3 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 262154 - 393226  , readahead: 4 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 393226 - 524298  , readahead: 5 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 524298 - 655370  , readahead: 6 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 655370 - 786442  , readahead: 7 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 786442 - 917514  , readahead: 8 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 917514 - 1048586  , readahead: 9 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1048586 - 1179658  , readahead: 10 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1179658 - 1310730  , readahead: 11 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1310730 - 1441802  , readahead: 12 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1441802 - 1572874  , readahead: 13 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1572874 - 1703946  , readahead: 14 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1703946 - 1835018  , readahead: 15 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1835018 - 1966090  , readahead: 16 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 1966090 - 2097162  , readahead: 17 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2097162 - 2228234  , readahead: 18 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2228234 - 2359306  , readahead: 19 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2359306 - 2490378  , readahead: 20 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2490378 - 2621450  , readahead: 21 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2621450 - 2752522  , readahead: 22 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2752522 - 2883594  , readahead: 23 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 2883594 - 3014666  , readahead: 24 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3014666 - 3145738  , readahead: 25 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3145738 - 3276810  , readahead: 26 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3276810 - 3407882  , readahead: 27 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3407882 - 3538954  , readahead: 28 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3538954 - 3670026  , readahead: 29 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3670026 - 3801098  , readahead: 30 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3801098 - 3932170  , readahead: 31 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 3932170 - 4063242  , readahead: 32 hits, 1 misses, 5242882 total requested bytes
DEBUG:fsspec:<File-like object HfFileSystem, datasets/allenai/c4@1588ec454efa1a09f29cd18ddd04fe05fc8653a2/en/c4-train.00000-of-01024.json.gz> read: 4063242 - 4194314  , readahead: 33 hits, 1 misses, 5242882 total requested bytes

{'text': 'Beginners BBQ Class Taking Place in Missoula!\nDo you want to get better at making delicious BBQ? You will have the opportunity, put this on your calendar now. Thursday, September 22nd join World Class BBQ Champion, Tony Balay from Lonestar Smoke Rangers. He will be teaching a beginner level class for everyone who wants to get better with their culinary skills.\nHe will teach you everything you need to know to compete in a KCBS BBQ competition, including techniques, recipes, timelines, meat selection and trimming, plus smoker and fire information.\nThe cost to be in the class is $35 per person, and for spectators it is free. Included in the cost will be either a t-shirt or apron and you will be tasting samples of each meat that is prepared.', 'timestamp': '2019-04-25 12:57:54', 'url': 'https://klyq.com/beginners-bbq-class-taking-place-in-missoula/'}
{'text': 'Discussion in \'Mac OS X Lion (10.7)\' started by axboi87, Jan 20, 2012.\nI\'ve got a 500gb internal drive and a 240gb SSD.\nWhen trying to restore using disk utility i\'m given the error "Not enough space on disk ____ to restore"\nBut I shouldn\'t have to do that!!!\nAny ideas or workarounds before resorting to the above?\nUse Carbon Copy Cloner to copy one drive to the other. I\'ve done this several times going from larger HDD to smaller SSD and I wound up with a bootable SSD drive. One step you have to remember not to skip is to use Disk Utility to partition the SSD as GUID partition scheme HFS+ before doing the clone. If it came Apple Partition Scheme, even if you let CCC do the clone, the resulting drive won\'t be bootable. CCC usually works in "file mode" and it can easily copy a larger drive (that\'s mostly empty) onto a smaller drive. If you tell CCC to clone a drive you did NOT boot from, it can work in block copy mode where the destination drive must be the same size or larger than the drive you are cloning from (if I recall).\nI\'ve actually done this somehow on Disk Utility several times (booting from a different drive (or even the dvd) so not running disk utility from the drive your cloning) and had it work just fine from larger to smaller bootable clone. Definitely format the drive cloning to first, as bootable Apple etc..\nThanks for pointing this out. My only experience using DU to go larger to smaller was when I was trying to make a Lion install stick and I was unable to restore InstallESD.dmg to a 4 GB USB stick but of course the reason that wouldn\'t fit is there was slightly more than 4 GB of data.', 'timestamp': '2019-04-21 10:07:13', 'url': 'https://forums.macrumors.com/threads/restore-from-larger-disk-to-smaller-disk.1311329/'}
{'text': 'Foil plaid lycra and spandex shortall with metallic slinky insets. Attached metallic elastic belt with O-ring. Headband included. Great hip hop or jazz dance costume. Made in the USA.', 'timestamp': '2019-04-25 10:40:23', 'url': 'https://awishcometrue.com/Catalogs/Clearance/Tweens/V1960-Find-A-Way'}
{'text': "How many backlinks per day for new site?\nDiscussion in 'Black Hat SEO' started by Omoplata, Dec 3, 2010.\n1) for a newly created site, what's the max # backlinks per day I should do to be safe?\n2) how long do I have to let my site age before I can start making more blinks?\nI did about 6000 forum profiles every 24 hours for 10 days for one of my sites which had a brand new domain.\nThere is three backlinks for every of these forum profile so thats 18 000 backlinks every 24 hours and nothing happened in terms of being penalized or sandboxed. This is now maybe 3 months ago and the site is ranking on first page for a lot of my targeted keywords.\nbuild more you can in starting but do manual submission and not spammy type means manual + relevant to the post.. then after 1 month you can make a big blast..\nWow, dude, you built 18k backlinks a day on a brand new site? How quickly did you rank up? What kind of competition/searches did those keywords have?", 'timestamp': '2019-04-21 12:46:19', 'url': 'https://www.blackhatworld.com/seo/how-many-backlinks-per-day-for-new-site.258615/'}
{'text': 'The Denver Board of Education opened the 2017-18 school year with an update on projects that include new construction, upgrades, heat mitigation and quality learning environments.\nWe are excited that Denver students will be the beneficiaries of a four year, $572 million General Obligation Bond. Since the passage of the bond, our construction team has worked to schedule the projects over the four-year term of the bond.\nDenver voters on Tuesday approved bond and mill funding measures for students in Denver Public Schools, agreeing to invest $572 million in bond funding to build and improve schools and $56.6 million in operating dollars to support proven initiatives, such as early literacy.\nDenver voters say yes to bond and mill levy funding support for DPS students and schools. Click to learn more about the details of the voter-approved bond measure.\nDenver voters on Nov. 8 approved bond and mill funding measures for DPS students and schools. Learn more about what’s included in the mill levy measure.', 'timestamp': '2019-04-20 14:33:21', 'url': 'http://bond.dpsk12.org/category/news/'}

In [185]:
filename = "lamini_docs.jsonl"
instruction_dataset_df = pd.read_json(filename, lines=True)
instruction_dataset_df

,question,answer
0,What are the different types of documents avai...,"Lamini has documentation on Getting Started, A..."
1,What is the recommended way to set up and conf...,Lamini can be downloaded as a python package a...
2,How can I find the specific documentation I ne...,"You can ask this model about documentation, wh..."
3,Does the documentation include explanations of...,Our documentation provides both real-world and...
4,Does the documentation provide information abo...,External dependencies and libraries are all av...
...,...,...
1395,What is Lamini and what is its collaboration w...,Lamini is a library that simplifies the proces...
1396,How does Lamini simplify the process of access...,Lamini simplifies data access in Databricks by...
1397,What are some of the key features provided by ...,Lamini automatically manages the infrastructur...
1398,How does Lamini ensure data privacy during the...,"During the training process, Lamini ensures da..."
1399,Can you provide an example use case where Lami...,An example use case where Lamini outperforms C...

In [186]:
examples = instruction_dataset_df.to_dict()
text = examples["question"][0] + examples["answer"][0]
text

"What are the different types of documents available in the repository (e.g., installation guide, API documentation, developer's guide)?Lamini has documentation on Getting Started, Authentication, Question Answer Model, Python Library, Batching, Error Handling, Advanced topics, and class documentation on LLM Engine available at https://lamini-ai.github.io/."

In [187]:
if "question" in examples and "answer" in examples:
  text = examples["question"][0] + examples["answer"][0]
elif "instruction" in examples and "response" in examples:
  text = examples["instruction"][0] + examples["response"][0]
elif "input" in examples and "output" in examples:
  text = examples["input"][0] + examples["output"][0]
else:
  text = examples["text"][0]

In [188]:
prompt_template_qa = """### Question:
{question}

### Answer:
{answer}"""

In [189]:
question = examples["question"][0]
answer = examples["answer"][0]

text_with_prompt_template = prompt_template_qa.format(question=question, answer=answer)
text_with_prompt_template

"### Question:\nWhat are the different types of documents available in the repository (e.g., installation guide, API documentation, developer's guide)?\n\n### Answer:\nLamini has documentation on Getting Started, Authentication, Question Answer Model, Python Library, Batching, Error Handling, Advanced topics, and class documentation on LLM Engine available at https://lamini-ai.github.io/."

In [190]:
prompt_template_q = """### Question:
{question}

### Answer:"""

In [191]:
num_examples = len(examples["question"])
finetuning_dataset_text_only = []
finetuning_dataset_question_answer = []
for i in range(num_examples):
  question = examples["question"][i]
  answer = examples["answer"][i]

  text_with_prompt_template_qa = prompt_template_qa.format(question=question, answer=answer)
  finetuning_dataset_text_only.append({"text": text_with_prompt_template_qa})

  text_with_prompt_template_q = prompt_template_q.format(question=question)
  finetuning_dataset_question_answer.append({"question": text_with_prompt_template_q, "answer": answer})

In [192]:
pprint(finetuning_dataset_text_only[0])

{'text': '### Question:\n'
         'What are the different types of documents available in the '
         "repository (e.g., installation guide, API documentation, developer's "
         'guide)?\n'
         '\n'
         '### Answer:\n'
         'Lamini has documentation on Getting Started, Authentication, '
         'Question Answer Model, Python Library, Batching, Error Handling, '
         'Advanced topics, and class documentation on LLM Engine available at '
         'https://lamini-ai.github.io/.'}

In [193]:
pprint(finetuning_dataset_question_answer[0])

{'answer': 'Lamini has documentation on Getting Started, Authentication, '
           'Question Answer Model, Python Library, Batching, Error Handling, '
           'Advanced topics, and class documentation on LLM Engine available '
           'at https://lamini-ai.github.io/.',
 'question': '### Question:\n'
             'What are the different types of documents available in the '
             'repository (e.g., installation guide, API documentation, '
             "developer's guide)?\n"
             '\n'
             '### Answer:'}

In [194]:
with jsonlines.open(f'lamini_docs_processed.jsonl', 'w') as writer:
    writer.write_all(finetuning_dataset_question_answer)

In [195]:
finetuning_dataset_name = "lamini/lamini_docs"
finetuning_dataset = load_dataset(finetuning_dataset_name)
print(finetuning_dataset)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'249'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md?%2Fdatasets%2Flamini%2Flamini_docs%2Fresolve%2Fmain%2FREADME.md=&etag=%22e2ced51e1b668a09d8a4f5fa9cd381dacad5a754%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b390-7d7fbf4a11e485cb77688761;d9f24747-5c54-461f-af03-216e67e5719c'), (b'RateLimit', b'"resolvers";r=2994;t=16'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'q5U83WKrbQD64LjhZyHvStPO1lFbREdkk454tIMhf-OMz9GBH3KNjA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'577'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 17:46:33 GMT'), (b'ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a722579-35c31b1c31dae84224fba867;69a45d97-fa66-4324-b301-48948aa806a3'), (b'RateLimit', b'"resolvers";r=2919;t=229'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'9O3Qo8MjUeMO_tRvmrdh7sgiUg_qy76xFOVsplDYdCk8b4gBO1gNYQ=='), (b'Age', b'298519')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b390-0149edcc69b272cb703f98a2;46e2b62a-63b4-4e4d-9d03-55fac071afe9'), (b'RateLimit', b'"resolvers";r=2993;t=16'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'JaJyKxQyrlVdjqK89kbu7NCPgzfnJEHJLtwlgOaoI-TtJelGd04ygQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'VA5Z2V9D8J7S9M2Q'), (b'x-amz-id-2', b'4VU8SgokOgSRcHSOBZh/7cOebtv2qaTkg5Yl7zLnaAhj43VdRGt+5lipDpwetZDkkbG8VI4WPII='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs/lamini/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b390-38493a486b9e914e1da48bf2;3a575e1d-8ead-449f-b370-312a99e418dc'), (b'RateLimit', b'"resolvers";r=2992;t=16'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'1yn1SvVmkqB3Eym_QXgRcI42Ww4jksLUNHExECpi2qoRIzSpxjjU9g==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f9dd0591c3cff00622aed9c3c625d64a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'gyBZPCV55OvcqCXmOqhoEvIlJjAKnHt54RgIv9R4C_BFP0fa7cqJCQ==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b390-52e5382d430e6149067c81b7;2e03251c-7fe1-48bd-8181-f1b8e2947793'), (b'RateLimit', b'"resolvers";r=2991;t=16'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'o4NeTCc5aVR2SM2KTbnuCoTc-cevxZH02UMmysArz0W_t3ViTKv13A==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1260
    })
    test: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 140
    })
})

In [196]:
instruction_tuned_dataset = load_dataset("tatsu-lab/alpaca", split="train", streaming=True)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'245'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'Location', b'/api/resolve-cache/datasets/tatsu-lab/alpaca/dce01c9b08f87459cf36a430d809084718273017/README.md?%2Fdatasets%2Ftatsu-lab%2Falpaca%2Fresolve%2Fmain%2FREADME.md=&etag=%2285e528790f89572cf48ee0383c6bc76241bc2cbd%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b391-4eb930be099a9cf64068b058;ae49d6b1-c5b6-4555-b867-16dc843f562d'), (b'RateLimit', b'"resolvers";r=2990;t=15'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"85e528790f89572cf48ee0383c6bc76241bc2cbd"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'TKkRFoPyh5LYS8Fz1JvTFZIDcYrCNJQf1GysEwY-Ge1-hg4RksySXA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'7472'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 19 Nov 2025 17:20:59 GMT'), (b'ETag', b'"85e528790f89572cf48ee0383c6bc76241bc2cbd"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-691dfc7b-7fa10df47d9bf868019a8533;0cab4023-6976-4adb-9aa3-68754370a932'), (b'RateLimit', b'"resolvers";r=2153;t=165'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'yC9IJ4Nb39g6B7FLNj9szH_u1q2OvV5d14ZiehE1yMP8atIrIoPA4Q=='), (b'Age', b'22591254')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/tatsu-lab/alpaca/dce01c9b08f87459cf36a430d809084718273017/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b391-57b2d80d184a5fb718a38422;2c6757fa-0a76-454a-b16a-8397409b8e4e'), (b'RateLimit', b'"resolvers";r=2989;t=15'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ig5Teeo8gbAp3mpBNt5-1yoJKcppwlEr9rHHNDgxGAJGi1U4oB7yfQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/alpaca.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'1KAF0S6T22FD2064'), (b'x-amz-id-2', b'bI4rwDmVKuti8dvDCK5XIXNLVBwc59cur3KWA1Z/z1Z31RWcR/JyqSzxfx45C3mnDt6Com+sbIw='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:41:52 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/tatsu-lab/alpaca/tatsu-lab/alpaca.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b391-6a72e20a37025c4f3dcf1a8b;3cd6d915-fdb6-4ae5-9530-33112ec0c14d'), (b'RateLimit', b'"resolvers";r=2988;t=15'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'2UAXkg3nmzFYpctIk7xkrBgacXUIGtizeQx-6IrFeey5wp-XZb4gKA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'dce01c9b08f87459cf36a430d809084718273017'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f9dd0591c3cff00622aed9c3c625d64a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'c1Mh3DtLb_7tCbLTL1h-UgTzW_p1ARxRN2yLzkUo3DKwoLyOngo7MQ==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=tatsu-lab/alpaca "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b391-734febb117bd2cdc4efa6595;da72dadd-7038-4b0e-8ffa-1751d5043154'), (b'RateLimit', b'"resolvers";r=2987;t=15'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'kUXXT7yGmYgWCy2ayhERNhueih6DGn9Esu1Uus-9WKnnngsIshZrOw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [197]:
m = 5
print("Instruction-tuned dataset:")
top_m = list(itertools.islice(instruction_tuned_dataset, m))
for j in top_m:
  print(j)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 302, b'Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'1192'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'Location', b'https://us.aws.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?X-Xet-Cas-Uid=public&user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&Expires=1786167713&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD9YLVhldC1DYXMtVWlkPXB1YmxpYyZ1c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3dHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTNCK2ZpbGVuYW1lJTNEJTIydHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTIyJTNCIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3ODYxNjc3MTN9LCJCeXRlUmFuZ2UiOnsiRXhwZWN0ZWRIZWFkZXIiOiJieXRlcz0yNDE4MTEwMi0yNDI0NjYzNyJ9fX1dfQ__&Signature=MEUCIHlyApZYmol2%7EBy6X42DyLYr-edJjnciIDN611ypryE-AiEAuWoi7L5o-kyWujr91fkAaqkXac1YY9Zf7%7EVo6EzGRcc_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b391-72b7097e507d268c4debab46;4c7718f8-1a96-4197-806c-8ec0c00f91fd'), (b'RateLimit', b'"resolvers";r=2986;t=15'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Linked-Size', b'24246638'), (b'X-Linked-ETag', b'"06391b656a06fd3fb9d213160ef2398796c3b7f3dc75ef1e3ced30d461517073"'), (b'Cache-Control', b'no-store'), (b'X-Xet-Hash', b'81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a'), (b'Link', b'<https://huggingface.co/api/datasets/tatsu-lab/alpaca/xet-read-token/dce01c9b08f87459cf36a430d809084718273017>; rel="xet-auth", <https://cas-server.xethub.hf.co/v1/reconstructions/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a>; rel="xet-reconstruction-info"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'RUukI_AnPOlYfdGXFfcfowbFx_DadESsY-QkOMeIfcJwMwEB-gGiDw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet "HTTP/1.1 302 Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='us.aws.cdn.hf.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2fe7eed0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='us.aws.cdn.hf.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b380919a0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>

Instruction-tuned dataset:

DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 206, b'Partial Content', [(b'content-type', b'application/octet-stream'), (b'accept-ranges', b'bytes'), (b'content-disposition', b'inline; filename*=UTF-8\'\'train-00000-of-00001-a09b74b3ef9c3b56.parquet; filename="train-00000-of-00001-a09b74b3ef9c3b56.parquet";'), (b'etag', b'"81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a"'), (b'access-control-allow-headers', b'Content-Range, Content-Type, Content-Disposition, ETag'), (b'access-control-expose-headers', b'*'), (b'content-length', b'65536'), (b'content-range', b'bytes 24181102-24246637/24246638'), (b'vary', b'origin, access-control-request-method, access-control-request-headers'), (b'access-control-allow-origin', b'*'), (b'x-request-id', b'01KZFTTWD4Q0YE63JYRVK2DR2G'), (b'x-hf-cdn-pop', b'aws-us-west-2'), (b'date', b'Sat, 08 Aug 2026 04:41:53 GMT'), (b'alt-svc', b'h3=":443";ma=60;')])
INFO:httpx:HTTP Request: GET https://us.aws.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?X-Xet-Cas-Uid=public&user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&Expires=1786167713&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD9YLVhldC1DYXMtVWlkPXB1YmxpYyZ1c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3dHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTNCK2ZpbGVuYW1lJTNEJTIydHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTIyJTNCIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3ODYxNjc3MTN9LCJCeXRlUmFuZ2UiOnsiRXhwZWN0ZWRIZWFkZXIiOiJieXRlcz0yNDE4MTEwMi0yNDI0NjYzNyJ9fX1dfQ__&Signature=MEUCIHlyApZYmol2%7EBy6X42DyLYr-edJjnciIDN611ypryE-AiEAuWoi7L5o-kyWujr91fkAaqkXac1YY9Zf7%7EVo6EzGRcc_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F "HTTP/1.1 206 Partial Content"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec:<File-like object HfFileSystem, datasets/tatsu-lab/alpaca@dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet> read: 24181102 - 24246638  , readahead: 0 hits, 1 misses, 65536 total requested bytes
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 302, b'Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'1190'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:54 GMT'), (b'Location', b'https://us.aws.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&X-Xet-Cas-Uid=public&Expires=1786167714&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD91c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3dHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTNCK2ZpbGVuYW1lJTNEJTIydHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTIyJTNCJlgtWGV0LUNhcy1VaWQ9cHVibGljIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3ODYxNjc3MTR9LCJCeXRlUmFuZ2UiOnsiRXhwZWN0ZWRIZWFkZXIiOiJieXRlcz0yNDE0NTQzNy0yNDI0NjYzNyJ9fX1dfQ__&Signature=MEUCIBzLWxY7pP0BVVnNwxOixYrs8Uo0UEFDpL0QlfsUM0g3AiEA49W8x442kneMY8wEQVNZUJ8W5ZzVzU%7EJAqdKmiCf5Ik_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b392-5bea3704774e4dfb4c6dfc37;1942ed06-d3d4-4a0b-aa42-f3d02f442070'), (b'RateLimit', b'"resolvers";r=2985;t=14'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Linked-Size', b'24246638'), (b'X-Linked-ETag', b'"06391b656a06fd3fb9d213160ef2398796c3b7f3dc75ef1e3ced30d461517073"'), (b'Cache-Control', b'no-store'), (b'X-Xet-Hash', b'81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a'), (b'Link', b'<https://huggingface.co/api/datasets/tatsu-lab/alpaca/xet-read-token/dce01c9b08f87459cf36a430d809084718273017>; rel="xet-auth", <https://cas-server.xethub.hf.co/v1/reconstructions/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a>; rel="xet-reconstruction-info"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'GYDVrDSbEsknd3SkKzlHnRCV2s4_NKiqBCRr8n2-WBhXpFSbXsu2FQ==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet "HTTP/1.1 302 Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 206, b'Partial Content', [(b'content-type', b'application/octet-stream'), (b'accept-ranges', b'bytes'), (b'content-disposition', b'inline; filename*=UTF-8\'\'train-00000-of-00001-a09b74b3ef9c3b56.parquet; filename="train-00000-of-00001-a09b74b3ef9c3b56.parquet";'), (b'etag', b'"81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a"'), (b'access-control-allow-headers', b'Content-Range, Content-Type, Content-Disposition, ETag'), (b'access-control-expose-headers', b'*'), (b'content-length', b'101201'), (b'content-range', b'bytes 24145437-24246637/24246638'), (b'vary', b'origin, access-control-request-method, access-control-request-headers'), (b'access-control-allow-origin', b'*'), (b'x-request-id', b'01KZFTTWSV4E0T79W6HP22SN38'), (b'x-hf-cdn-pop', b'aws-us-west-2'), (b'date', b'Sat, 08 Aug 2026 04:41:54 GMT'), (b'alt-svc', b'h3=":443";ma=60;')])
INFO:httpx:HTTP Request: GET https://us.aws.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?user_id=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&X-Xet-Cas-Uid=public&Expires=1786167714&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD91c2VyX2lkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3dHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTNCK2ZpbGVuYW1lJTNEJTIydHJhaW4tMDAwMDAtb2YtMDAwMDEtYTA5Yjc0YjNlZjljM2I1Ni5wYXJxdWV0JTIyJTNCJlgtWGV0LUNhcy1VaWQ9cHVibGljIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJFcG9jaFRpbWUiOjE3ODYxNjc3MTR9LCJCeXRlUmFuZ2UiOnsiRXhwZWN0ZWRIZWFkZXIiOiJieXRlcz0yNDE0NTQzNy0yNDI0NjYzNyJ9fX1dfQ__&Signature=MEUCIBzLWxY7pP0BVVnNwxOixYrs8Uo0UEFDpL0QlfsUM0g3AiEA49W8x442kneMY8wEQVNZUJ8W5ZzVzU%7EJAqdKmiCf5Ik_&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F "HTTP/1.1 206 Partial Content"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec:<File-like object HfFileSystem, datasets/tatsu-lab/alpaca@dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet> read: 24145437 - 24246630  , readahead: 0 hits, 2 misses, 166737 total requested bytes
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 302, b'Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'982'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:54 GMT'), (b'Location', b'https://us.gcp.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&user_id=public&X-Xet-Cas-Uid=public&Expires=1786167714&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomdXNlcl9pZD1wdWJsaWMmWC1YZXQtQ2FzLVVpZD1wdWJsaWMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc4NjE2NzcxNH0sIkJ5dGVSYW5nZSI6eyJFeHBlY3RlZEhlYWRlciI6ImJ5dGVzPTQtMjQyNDY2MzcifX19XX0_&Signature=MEQCICJGD4AfRhzNWtpSJicoD1eQ2JtImqCcwJJMkhbbb089AiBGcimebVTuzr9YH6T50DzL8Sg9wcBnarWa5KM5%7EGTAtQ__&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b392-744bfb692ae791ab1e570300;0384d301-026e-4863-9e6e-45dd697ad6e1'), (b'RateLimit', b'"resolvers";r=2984;t=14'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'dce01c9b08f87459cf36a430d809084718273017'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Linked-Size', b'24246638'), (b'X-Linked-ETag', b'"06391b656a06fd3fb9d213160ef2398796c3b7f3dc75ef1e3ced30d461517073"'), (b'Cache-Control', b'no-store'), (b'X-Xet-Hash', b'81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a'), (b'Link', b'<https://huggingface.co/api/datasets/tatsu-lab/alpaca/xet-read-token/dce01c9b08f87459cf36a430d809084718273017>; rel="xet-auth", <https://cas-server.xethub.hf.co/v1/reconstructions/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a>; rel="xet-reconstruction-info"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ddRw9rc2HlJYYFPsDWHzxfEDdNxShdbVxeYxyMq-XHbkCWWs-6iJXg==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/datasets/tatsu-lab/alpaca/resolve/dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet "HTTP/1.1 302 Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 206, b'Partial Content', [(b'content-type', b'application/octet-stream'), (b'accept-ranges', b'bytes'), (b'content-disposition', b'inline; filename*=UTF-8\'\'train-00000-of-00001-a09b74b3ef9c3b56.parquet; filename="train-00000-of-00001-a09b74b3ef9c3b56.parquet";'), (b'etag', b'"81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a"'), (b'access-control-allow-headers', b'Content-Range, Content-Type, Content-Disposition, ETag'), (b'access-control-expose-headers', b'*'), (b'Content-Length', b'24246634'), (b'content-range', b'bytes 4-24246637/24246638'), (b'vary', b'origin, access-control-request-method, access-control-request-headers'), (b'access-control-allow-origin', b'*'), (b'x-request-id', b'01KZFTTX4V2JK4W35747CMBNZP'), (b'x-hf-cdn-pop', b'gcp-us-west4'), (b'date', b'Sat, 08 Aug 2026 04:41:54 GMT'), (b'via', b'1.1 google'), (b'Alt-Svc', b'h3=":443"; ma=2592000')])
INFO:httpx:HTTP Request: GET https://us.gcp.cdn.hf.co/xet-bridge-us/640f5b2fb63b6f18522d6d44/81a195eff63cba56576b3d5f08b0a314f77564e45787e2ffafcea980e9e13b3a?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27train-00000-of-00001-a09b74b3ef9c3b56.parquet%3B+filename%3D%22train-00000-of-00001-a09b74b3ef9c3b56.parquet%22%3B&user_id=public&X-Xet-Cas-Uid=public&Expires=1786167714&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5nY3AuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQwZjViMmZiNjNiNmYxODUyMmQ2ZDQ0LzgxYTE5NWVmZjYzY2JhNTY1NzZiM2Q1ZjA4YjBhMzE0Zjc3NTY0ZTQ1Nzg3ZTJmZmFmY2VhOTgwZTllMTNiM2FcXD9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPSomdXNlcl9pZD1wdWJsaWMmWC1YZXQtQ2FzLVVpZD1wdWJsaWMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkVwb2NoVGltZSI6MTc4NjE2NzcxNH0sIkJ5dGVSYW5nZSI6eyJFeHBlY3RlZEhlYWRlciI6ImJ5dGVzPTQtMjQyNDY2MzcifX19XX0_&Signature=MEQCICJGD4AfRhzNWtpSJicoD1eQ2JtImqCcwJJMkhbbb089AiBGcimebVTuzr9YH6T50DzL8Sg9wcBnarWa5KM5%7EGTAtQ__&Key-Pair-Id=01KXEF4KZ1B6FV465MAWR4M21F "HTTP/1.1 206 Partial Content"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec:<File-like object HfFileSystem, datasets/tatsu-lab/alpaca@dce01c9b08f87459cf36a430d809084718273017/data/train-00000-of-00001-a09b74b3ef9c3b56.parquet> read: 4 - 24143226  , readahead: 0 hits, 3 misses, 24413371 total requested bytes

{'instruction': 'Give three tips for staying healthy.', 'input': '', 'output': '1.Eat a balanced diet and make sure to include plenty of fruits and vegetables. \n2. Exercise regularly to keep your body active and strong. \n3. Get enough sleep and maintain a consistent sleep schedule.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nGive three tips for staying healthy.\n\n### Response:\n1.Eat a balanced diet and make sure to include plenty of fruits and vegetables. \n2. Exercise regularly to keep your body active and strong. \n3. Get enough sleep and maintain a consistent sleep schedule.'}
{'instruction': 'What are the three primary colors?', 'input': '', 'output': 'The three primary colors are red, blue, and yellow.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nWhat are the three primary colors?\n\n### Response:\nThe three primary colors are red, blue, and yellow.'}
{'instruction': 'Describe the structure of an atom.', 'input': '', 'output': 'An atom is made up of a nucleus, which contains protons and neutrons, surrounded by electrons that travel in orbits around the nucleus. The protons and neutrons have a positive charge, while the electrons have a negative charge, resulting in an overall neutral atom. The number of each particle determines the atomic number and the type of atom.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nDescribe the structure of an atom.\n\n### Response:\nAn atom is made up of a nucleus, which contains protons and neutrons, surrounded by electrons that travel in orbits around the nucleus. The protons and neutrons have a positive charge, while the electrons have a negative charge, resulting in an overall neutral atom. The number of each particle determines the atomic number and the type of atom.'}
{'instruction': 'How can we reduce air pollution?', 'input': '', 'output': 'There are a number of ways to reduce air pollution, such as shifting to renewable energy sources, encouraging the use of public transportation, prohibiting the burning of fossil fuels, implementing policies to reduce emissions from industrial sources, and implementing vehicle emissions standards. Additionally, individuals can do their part to reduce air pollution by reducing car use, avoiding burning materials such as wood, and changing to energy efficient appliances.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nHow can we reduce air pollution?\n\n### Response:\nThere are a number of ways to reduce air pollution, such as shifting to renewable energy sources, encouraging the use of public transportation, prohibiting the burning of fossil fuels, implementing policies to reduce emissions from industrial sources, and implementing vehicle emissions standards. Additionally, individuals can do their part to reduce air pollution by reducing car use, avoiding burning materials such as wood, and changing to energy efficient appliances.'}
{'instruction': 'Describe a time when you had to make a difficult decision.', 'input': '', 'output': 'I had to make a difficult decision when I was working as a project manager at a construction company. I was in charge of a project that needed to be completed by a certain date in order to meet the client’s expectations. However, due to unexpected delays, we were not able to meet the deadline and so I had to make a difficult decision. I decided to extend the deadline, but I had to stretch the team’s resources even further and increase the budget. Although it was a risky decision, I ultimately decided to go ahead with it to ensure that the project was completed on time and that the client’s expectations were met. The project was eventually successfully completed and this was seen as a testament to my leadership and decision-making abilities.', 'text': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\nDescribe a time when you had to make a difficult decision.\n\n### Response:\nI had to make a difficult decision when I was working as a project manager at a construction company. I was in charge of a project that needed to be completed by a certain date in order to meet the client’s expectations. However, due to unexpected delays, we were not able to meet the deadline and so I had to make a difficult decision. I decided to extend the deadline, but I had to stretch the team’s resources even further and increase the budget. Although it was a risky decision, I ultimately decided to go ahead with it to ensure that the project was completed on time and that the client’s expectations were met. The project was eventually successfully completed and this was seen as a testament to my leadership and decision-making abilities.'}

In [198]:
prompt_template_with_input = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Input:
{input}

### Response:"""

prompt_template_without_input = """Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Response:"""

In [199]:
processed_data = []
for j in top_m:
  if not j["input"]:
    processed_prompt = prompt_template_without_input.format(instruction=j["instruction"])
  else:
    processed_prompt = prompt_template_with_input.format(instruction=j["instruction"], input=j["input"])

  processed_data.append({"input": processed_prompt, "output": j["output"]})

In [200]:
pprint(processed_data[0])

{'input': 'Below is an instruction that describes a task. Write a response '
          'that appropriately completes the request.\n'
          '\n'
          '### Instruction:\n'
          'Give three tips for staying healthy.\n'
          '\n'
          '### Response:',
 'output': '1.Eat a balanced diet and make sure to include plenty of fruits '
           'and vegetables. \n'
           '2. Exercise regularly to keep your body active and strong. \n'
           '3. Get enough sleep and maintain a consistent sleep schedule.'}

In [201]:
with jsonlines.open(f'alpaca_processed.jsonl', 'w') as writer:
    writer.write_all(processed_data)

In [202]:
dataset_path_hf = "lamini/alpaca"
dataset_hf = load_dataset(dataset_path_hf)
print(dataset_hf)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'239'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/alpaca/281908616970e0abcb4cb0c3d65a76a0f73944cd/README.md?%2Fdatasets%2Flamini%2Falpaca%2Fresolve%2Fmain%2FREADME.md=&etag=%22f0372e46c8cd0f7ab67484d6de6bb4d8d675014e%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-0b4fc361714771bc65215be3;2b3bd02d-ce11-438c-8f56-0e46bb0e379f'), (b'RateLimit', b'"resolvers";r=2983;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f0372e46c8cd0f7ab67484d6de6bb4d8d675014e"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'-1UzHYGHCtl_ehrqGxoXrv7OZ3dWYo0ZA0RDoJjSmHA7ftZB_b70bg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/alpaca/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'388'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 07 Aug 2026 13:21:48 GMT'), (b'ETag', b'"f0372e46c8cd0f7ab67484d6de6bb4d8d675014e"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a75dbec-6dca4fe2278ea2b473ba866a;c23bd7de-e393-4b70-b09f-30a8c2b3d9d3'), (b'RateLimit', b'"resolvers";r=2980;t=204'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'kPn-_VR80YPhTR7L16mZ2XctZRdLT2BKH3ZDw_gq947zzvdcWEaqQA=='), (b'Age', b'55207')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/alpaca/281908616970e0abcb4cb0c3d65a76a0f73944cd/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-2c53817546cf52881f8a164e;a9e7fbb7-4612-4d70-9c14-1bff23e1da2b'), (b'RateLimit', b'"resolvers";r=2982;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'HaAvPHLzOJxQ6yvbUVbKkk2NnzAPd1HcZVvZJf4mOc4mWFzftaf0BA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/alpaca/resolve/281908616970e0abcb4cb0c3d65a76a0f73944cd/alpaca.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'G9CGMJ9XV8W67EHD'), (b'x-amz-id-2', b'JUiv7w1brX/gql4U3p6myo4H4iTRed0L94b11gkLEyHTwmFgUaHW4gfgXbb8J9Rgq89H12dqVO0='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:41:54 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/alpaca/lamini/alpaca.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-7f91a41675f6a9044545f24c;6fbde881-3d00-451a-98a5-35d7b1e3dcbe'), (b'RateLimit', b'"resolvers";r=2981;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BtQHKusuf17rqefV6ovYO5-OxypFznMs4RfG9l_HnnauLzmgMf6kIQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/alpaca/resolve/281908616970e0abcb4cb0c3d65a76a0f73944cd/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f9dd0591c3cff00622aed9c3c625d64a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'4yi_YoJNQhceTuI2xe76kWB5_XKK7sNR4BewaVt1rau2lWqk_YCXiQ==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/alpaca "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-69d911dd3a58f033047fb608;47f1e3a0-d005-4330-9e9a-076ecda1d2e1'), (b'RateLimit', b'"resolvers";r=2980;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'281908616970e0abcb4cb0c3d65a76a0f73944cd'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'eXsNhpQ6oiV88JFkNpuIobnvDr1UpkhQK466KJdcqqIGt_uxtQpJbQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/alpaca/resolve/281908616970e0abcb4cb0c3d65a76a0f73944cd/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___alpaca/default/0.0.0/281908616970e0abcb4cb0c3d65a76a0f73944cd/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___alpaca/default/0.0.0/281908616970e0abcb4cb0c3d65a76a0f73944cd/dataset_info.json

DatasetDict({
    train: Dataset({
        features: ['input', 'output'],
        num_rows: 52002
    })
})

In [203]:
non_instruct_model = BasicModelRunner("meta-llama/Llama-2-7b-hf")
non_instruct_output = non_instruct_model("Tell me how to train my dog to sit")
print("Not instruction-tuned output (Llama 2 Base):", non_instruct_output)

Not instruction-tuned output (Llama 2 Base): Tell me how to train my dog to stay.
Tell me how to teach my dog to come.
Tell me how to get my dog to heel.
Tell me how to stop my dog from jumping.
Tell me how to make my dog stop barking.
Tell me how I can get my dog to stop chewing.
Tell me how to house train my dog.
Tell me how to potty train my dog.
Tell me how to train my dog to walk on a leash.
Tell me how to crate train my dog.
Tell Me How To Train My Dog To Sit, Stay, Come, Heel, Stop Jumping, Stop Barking, Stop Chewing, House Train, Potty Train, Walk On A Leash, Crate Train, And More!
Tell Me How To Train Your Dog To Sit, Stay, Heel, Come, Stop Jumping, Stop Chewing, House Trained, Potty Trained, Walk On A Leash, And More!
Tell me how to train your dog to sit.
Tell Me How To House Train My Dog.

In [204]:
instruct_model = BasicModelRunner("meta-llama/Llama-2-7b-chat-hf")
instruct_output = instruct_model("Tell me how to train my dog to sit")
print("Instruction-tuned output (Llama 2): ", instruct_output)

Instruction-tuned output (Llama 2):  on command. Training your dog to sit is a basic obedience command that can be achieved with patience, consistency, and positive reinforcement. Here's a step-by-step guide on how to train your dog to sit:

1. Choose a quiet and distraction-free area: Find a quiet room or area where your dog can focus on you without getting distracted.
2. Have treats ready: Choose your dog's favorite treats and have them readily available to reward good behavior.
3. Stand in front of your dog: Stand in front of your dog and hold a treat close to their nose.
4. Move the treat up and back: Slowly move the treat upwards and backwards, towards your dog's tail, while saying "sit" in a calm and clear voice.
5. Dog will follow the treat: As you move the treat, your dog should naturally sit down to follow it. The moment they touch their bottom to the ground, give them the treat and praise them.

In [205]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [206]:
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-70m")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/pythia-70m")

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-01d1c41f40c9009e2080f4ec;95b0c3b4-2129-4f8f-a14c-47202f6355df'), (b'RateLimit', b'"resolvers";r=2979;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'-LsBpoj8p9yBchtsMrFANA9KvonsdiVXQB39Vg5Eem-GTuXTrimmxQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'VrGzR7TC3VtuAT4cD53pQdOAvm9-b-HjYwBHN26tJmV42Z1IXzg5SA=='), (b'Age', b'3849036')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'266'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22f1860edb10f80bcaf7b023fce47c68a23b724c23%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-3b9b0802585c46572ecd6d4f;201e98cd-0f1e-4693-8cb5-3c797390fb47'), (b'RateLimit', b'"resolvers";r=2978;t=13'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'A26TMPQ3F9W7sI40gnvzdiwUosVDjg_nbE1oR-wkrCxDCjTIBtAP5Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'396'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 25 Nov 2025 07:32:47 GMT'), (b'ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69255b9f-43c8b47b06ae4d4b7a5b6850;d0cf6526-71cd-486d-ab80-dbe3d2f787dd'), (b'RateLimit', b'"resolvers";r=2888;t=21'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'V3Uc9ejtORqZPiYLxxz0faA38mzHyvmk41N9kKHcMHFFv9nIzLVDxw=='), (b'Age', b'22108148')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:55 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b393-64a6c94c34d77b5665e698ed;a31a2d9f-fcda-486e-9f1f-4644a92bb752'), (b'RateLimit', b'"api";r=499;t=13'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'9h5BwfjJjm5rN2dSMBBc3pX96H_f5q-C5w31RUCczj0ZgxDfrixWug==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"4c3-dou0MC1Uk5uul8iexhdohgHrzho"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-15a0366e15932c9316ac706c;4190cfa3-05ed-4e30-90ff-b2dbc95e2875'), (b'RateLimit', b'"api";r=498;t=12'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'E7JipsETVH40gLStq-EyeVOl1oT1vzBgr2lgvaLnmlOPcv77TKhpdw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-353c5a07149b247918b83571;5f0eeecf-9295-4055-9dad-fe615e4c658d'), (b'RateLimit', b'"resolvers";r=2977;t=12'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'rU6CMnrpol39iiR6set7MxYM34iK97ctwTYVRHztduDfzPWw0l3dGw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'LXe7bcUCI8aj3qTlD8bRFWCaa1fdsxyF82f-z2MZCuO6E50ZXHW1iA=='), (b'Age', b'3849037')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-25a9b4c1633e30f63c6a9bff;066bf02f-981b-477b-9f5b-e428043386a0'), (b'RateLimit', b'"resolvers";r=2975;t=12'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'-qD3cmPOr3O7vhXAeogvnL7XYTKEseUfvsqPsJi3CBgD6le7O5HCww==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-30b7fd175aec9c6e0e5a195b;49bdc329-a9cc-4732-b33e-b38a55efd682'), (b'RateLimit', b'"resolvers";r=2974;t=12'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ySH1czM8I7lvYUThSwPvDO3q98gKfPipab6fZXmMk9_ERJN-E7i2rA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'N-R0CGCFVh6Utn0cAvt2UR675eSgOj4RS64FE1EY0kmMiSjyljAqqA=='), (b'Age', b'3849037')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [207]:
def inference(text, model, tokenizer, max_input_tokens=1000, max_output_tokens=100):
  # Tokenize
  input_ids = tokenizer.encode(
          text,
          return_tensors="pt",
          truncation=True,
          max_length=max_input_tokens
  )

  # Generate
  device = model.device
  generated_tokens_with_prompt = model.generate(
    input_ids=input_ids.to(device),
    max_length=max_output_tokens
  )

  # Decode
  generated_text_with_prompt = tokenizer.batch_decode(generated_tokens_with_prompt, skip_special_tokens=True)

  # Strip the prompt
  generated_text_answer = generated_text_with_prompt[0][len(text):]

  return generated_text_answer

In [208]:
finetuning_dataset_path = "lamini/lamini_docs"
finetuning_dataset = load_dataset(finetuning_dataset_path)
print(finetuning_dataset)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'249'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md?%2Fdatasets%2Flamini%2Flamini_docs%2Fresolve%2Fmain%2FREADME.md=&etag=%22e2ced51e1b668a09d8a4f5fa9cd381dacad5a754%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-50f187550a065a6a6d8af3fd;719127e5-67ae-4ce5-88b1-82b10db8a80e'), (b'RateLimit', b'"resolvers";r=2973;t=12'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'aGdAWnGLsZo4MK1ojhWO6KJGAn4hxLFX4PQACRzwbJudlgPrvoKxcw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'577'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 17:46:33 GMT'), (b'ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a722579-35c31b1c31dae84224fba867;69a45d97-fa66-4324-b301-48948aa806a3'), (b'RateLimit', b'"resolvers";r=2919;t=229'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'flQvq09_5-B4BzPayYMSNrKFjC807yggYqMqKCu0li_48Ms-3R9ISQ=='), (b'Age', b'298523')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b394-43cb5699632b7a6d45c22bb4;5c417359-8d2e-4830-94bf-e844ef95af1f'), (b'RateLimit', b'"resolvers";r=2972;t=12'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'5H-GsfvEmPKlFoSodChNKf_VkM6B46JxBAy905Nl7SgeqykUUCWYSA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'WPA2MP48VK0KV5V6'), (b'x-amz-id-2', b'0LsSPzerBaPgstAF0CY0xE5QkWZ026Y6IyS3Ve4FHyeJoVOC3oVsSGibhazobbDyGZYn4t3+M2I='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:41:56 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs/lamini/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:57 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b395-7760f3ee7f84595d2a4316d0;64bdb69b-b0bd-40c3-8a0f-68742af72914'), (b'RateLimit', b'"resolvers";r=2971;t=11'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'57gyB0iDEamKRz2V609SIoRWmgaUD0lc4aJDSBSgWG9ZcI3u9JGQtA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:57 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f9dd0591c3cff00622aed9c3c625d64a.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'Doe7dPn_SD0md520T3sxZQXbMYLH_I-F72heLwYgu3g_kPPMtDSp_g==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:41:57 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b395-6e1ad628720dc8ac1b735af3;d540eacd-c32e-4ab5-986a-2ed8a30144b7'), (b'RateLimit', b'"resolvers";r=2970;t=11'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'P9u2lOaicAwuoNDcNWFRdHmwBk547KVAmsPSK4ja5IhmfOYxUOMWjw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1260
    })
    test: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 140
    })
})

In [209]:
test_sample = finetuning_dataset["test"][0]
print(test_sample)

print(inference(test_sample["question"], model, tokenizer))

{'question': 'Can Lamini generate technical documentation or user manuals for software projects?', 'answer': 'Yes, Lamini can generate technical documentation and user manuals for software projects. It uses natural language generation techniques to create clear and concise documentation that is easy to understand for both technical and non-technical users. This can save developers a significant amount of time and effort in creating documentation, allowing them to focus on other aspects of their projects.', 'input_ids': [5804, 418, 4988, 74, 6635, 7681, 10097, 390, 2608, 11595, 84, 323, 3694, 6493, 32, 4374, 13, 418, 4988, 74, 476, 6635, 7681, 10097, 285, 2608, 11595, 84, 323, 3694, 6493, 15, 733, 4648, 3626, 3448, 5978, 5609, 281, 2794, 2590, 285, 44003, 10097, 326, 310, 3477, 281, 2096, 323, 1097, 7681, 285, 1327, 14, 48746, 4212, 15, 831, 476, 5321, 12259, 247, 1534, 2408, 273, 673, 285, 3434, 275, 6153, 10097, 13, 6941, 731, 281, 2770, 327, 643, 7794, 273, 616, 6493, 15], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [5804, 418, 4988, 74, 6635, 7681, 10097, 390, 2608, 11595, 84, 323, 3694, 6493, 32, 4374, 13, 418, 4988, 74, 476, 6635, 7681, 10097, 285, 2608, 11595, 84, 323, 3694, 6493, 15, 733, 4648, 3626, 3448, 5978, 5609, 281, 2794, 2590, 285, 44003, 10097, 326, 310, 3477, 281, 2096, 323, 1097, 7681, 285, 1327, 14, 48746, 4212, 15, 831, 476, 5321, 12259, 247, 1534, 2408, 273, 673, 285, 3434, 275, 6153, 10097, 13, 6941, 731, 281, 2770, 327, 643, 7794, 273, 616, 6493, 15]}


A:

I think the answer is to use a "manual" approach, but I don't think that's the right approach.

A:

I think the answer is to use a "manual" approach, but I don't think that's the right approach.

A:

I think the answer is to use a "manual" approach, but I don't think that

In [210]:
instruction_model = AutoModelForCausalLM.from_pretrained("lamini/lamini_docs_finetuned")

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:00 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b398-4eff08576d32791e1adfdaae;e193357e-116f-46a3-bbaf-3bb37db01abc'), (b'RateLimit', b'"resolvers";r=2969;t=8'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'kPk8TpxL5TdpUO6dlcCNzEiPeb-6ljC3UuyRqZGDiN63ZE4i7f3HZg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'JaLN4t7qmAv639nru0Yi0OPBjOIY_jvhbkZRmAMA7vN044mFk7lpAA=='), (b'Age', b'221941')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:00 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b398-30716ff427a37b0651ae55f4;f5fa002b-9af9-4164-b4df-9aaa09b2ba00'), (b'RateLimit', b'"resolvers";r=2968;t=8'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'nsAc9LIt7isyFitXymmUg0qKoab7Igj6y5va10nI6wqfK-Nh3ZDoqw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'MTXAeaXtcJPFUKaplnF69hx-FiKNFkHqrlIUDt4oV656D25jVXIUdQ=='), (b'Age', b'221941')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'282'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:00 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fgeneration_config.json=&etag=%22d1273fdfdec769418aa547e8e6f7174c523fed2f%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b398-5689c2ab070756f603f1ac80;f75594f4-e55d-4aba-9529-ef03886babe6'), (b'RateLimit', b'"resolvers";r=2967;t=8'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ota21IX3n_WTmrAmVl7T9zcH_ry4zd-Lbww1GbztSDX46kYaaII9MQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'111'), (b'Connection', b'keep-alive'), (b'Date', b'Mon, 03 Aug 2026 14:23:55 GMT'), (b'ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a70a47b-3268462d48af7e09781551ba;73a6a2d3-fc11-4f48-a8c5-801faa626ca1'), (b'RateLimit', b'"resolvers";r=2954;t=101'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'jVvvB1qsYCuvJrok3wPobfcnzOiMmsNLEjXjGIRTZm_Y-r4_RoIipA=='), (b'Age', b'397086')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [211]:
print(inference(test_sample["question"], instruction_model, tokenizer))

Yes, Lamini can generate technical documentation or user manuals for software projects. This can be achieved by providing a prompt for a specific technical question or question to the LLM Engine, or by providing a prompt for a specific technical question or question. Additionally, Lamini can be trained on specific technical questions or questions to help users understand the process and provide feedback to the LLM Engine. Additionally, Lamini

In [213]:
import pandas as pd
import datasets

from pprint import pprint
from transformers import AutoTokenizer

In [214]:
#tokenizing text
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-70m")

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:04 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b39c-36ebf8ad07574b183cac1a9e;5282794a-a43f-4c5e-b34f-112b540ee2d9'), (b'RateLimit', b'"resolvers";r=2966;t=4'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'j21zB19WBamsrFE6VMF-fWNOfb4-ER9tqdJSVeHhL19MtcKa-KrslA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'DrHZ3IFQ4KMnf6KzZFWnyaC6gcaEiWEErHykgr-X02Je1GQjfspFLw=='), (b'Age', b'3849045')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'266'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:04 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22f1860edb10f80bcaf7b023fce47c68a23b724c23%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b39c-6ba43de83ee44c7365e429f6;37980a5f-d9cd-411f-99d4-e3f3db7c2ffe'), (b'RateLimit', b'"resolvers";r=2965;t=4'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'k3d5vumMO2DaeD43kcMhZLWs6mjdaMv5jot0uzKeevPpASTtlNGomQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'396'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 25 Nov 2025 07:32:47 GMT'), (b'ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69255b9f-43c8b47b06ae4d4b7a5b6850;d0cf6526-71cd-486d-ab80-dbe3d2f787dd'), (b'RateLimit', b'"resolvers";r=2888;t=21'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'Ozcy3JytM_PtWGLRNbs0XwVhRzdxGZWAN76Mdf7p_Exlkb-B5pHn3Q=='), (b'Age', b'22108157')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:04 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b39c-423b785a6f793f922d5ca33d;aea6a7af-e590-4187-992e-403979676c80'), (b'RateLimit', b'"api";r=497;t=4'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'pJ_GFp_odREHiMpAUFlkmY-TmpIFgb0PEHXJV4Fi55q7yB-kIosTIg==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:05 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"4c3-dou0MC1Uk5uul8iexhdohgHrzho"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b39d-19cfbfd239ebcd165b30ffe0;8e76eabc-d48f-4fc0-a732-731d9840800d'), (b'RateLimit', b'"api";r=496;t=3'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 56f3eb40037bf45331af054618b17ca2.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'7vr3CfeUY3NQdEmhajtBh0A2ieuq-4josmWuHIz0K_DiCMsbqEB4uA==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [215]:
text = "Hi, how are you?"

In [216]:
encoded_text = tokenizer(text)["input_ids"]

In [217]:
encoded_text

[12764, 13, 849, 403, 368, 32]

In [218]:
decoded_text = tokenizer.decode(encoded_text)
print("Decoded tokens back into text: ", decoded_text)

Decoded tokens back into text:  Hi, how are you?

In [219]:
#tokenize multiple text
list_texts = ["Hi, how are you?", "I'm good", "Yes"]
encoded_texts = tokenizer(list_texts)
print("Encoded several texts: ", encoded_texts["input_ids"])

Encoded several texts:  [[12764, 13, 849, 403, 368, 32], [42, 1353, 1175], [4374]]

In [220]:
#padding,truncation
tokenizer.pad_token = tokenizer.eos_token
encoded_texts_longest = tokenizer(list_texts, padding=True)
print("Using padding: ", encoded_texts_longest["input_ids"])

Using padding:  [[12764, 13, 849, 403, 368, 32], [42, 1353, 1175, 0, 0, 0], [4374, 0, 0, 0, 0, 0]]

In [221]:
encoded_texts_truncation = tokenizer(list_texts, max_length=3, truncation=True)
print("Using truncation: ", encoded_texts_truncation["input_ids"])

Using truncation:  [[12764, 13, 849], [42, 1353, 1175], [4374]]

In [222]:
tokenizer.truncation_side = "left"
encoded_texts_truncation_left = tokenizer(list_texts, max_length=3, truncation=True)
print("Using left-side truncation: ", encoded_texts_truncation_left["input_ids"])

Using left-side truncation:  [[403, 368, 32], [42, 1353, 1175], [4374]]

In [223]:
encoded_texts_both = tokenizer(list_texts, max_length=3, truncation=True, padding=True)
print("Using both padding and truncation: ", encoded_texts_both["input_ids"])

Using both padding and truncation:  [[403, 368, 32], [42, 1353, 1175], [4374, 0, 0]]

In [224]:
#prepare instruction dataset
import pandas as pd

filename = "lamini_docs.jsonl"
instruction_dataset_df = pd.read_json(filename, lines=True)
examples = instruction_dataset_df.to_dict()

if "question" in examples and "answer" in examples:
  text = examples["question"][0] + examples["answer"][0]
elif "instruction" in examples and "response" in examples:
  text = examples["instruction"][0] + examples["response"][0]
elif "input" in examples and "output" in examples:
  text = examples["input"][0] + examples["output"][0]
else:
  text = examples["text"][0]

prompt_template = """### Question:
{question}

### Answer:"""

num_examples = len(examples["question"])
finetuning_dataset = []
for i in range(num_examples):
  question = examples["question"][i]
  answer = examples["answer"][i]
  text_with_prompt_template = prompt_template.format(question=question)
  finetuning_dataset.append({"question": text_with_prompt_template, "answer": answer})

from pprint import pprint
print("One datapoint in the finetuning dataset:")
pprint(finetuning_dataset[0])

One datapoint in the finetuning dataset:
{'answer': 'Lamini has documentation on Getting Started, Authentication, '
           'Question Answer Model, Python Library, Batching, Error Handling, '
           'Advanced topics, and class documentation on LLM Engine available '
           'at https://lamini-ai.github.io/.',
 'question': '### Question:\n'
             'What are the different types of documents available in the '
             'repository (e.g., installation guide, API documentation, '
             "developer's guide)?\n"
             '\n'
             '### Answer:'}

In [225]:
#tokenize a single example
text = finetuning_dataset[0]["question"] + finetuning_dataset[0]["answer"]
tokenized_inputs = tokenizer(
    text,
    return_tensors="np",
    padding=True
)
print(tokenized_inputs["input_ids"])

[[ 4118 19782    27   187  1276   403   253  1027  3510   273  7177  2130
    275   253 18491   313    70    15    72   904 12692  7102    13  8990
  10097    13 13722   434  7102  6177   187   187  4118 37741    27    45
   4988    74   556 10097   327 27669 11075   264    13  5271 23058    13
  19782 37741 10031    13 13814 11397    13   378 16464    13 11759 10535
   1981    13 21798 12989    13   285   966 10097   327 21708    46 10797
   2130   387  5987  1358    77  4988    74    14  2284    15  7280    15
    900 14206]]

In [226]:
max_length = 2048
max_length = min(
    tokenized_inputs["input_ids"].shape[1],
    max_length,
)

In [227]:
tokenized_inputs = tokenizer(
    text,
    return_tensors="np",
    truncation=True,
    max_length=max_length
)

In [228]:
tokenized_inputs["input_ids"]

array([[ 4118, 19782,    27,   187,  1276,   403,   253,  1027,  3510,
          273,  7177,  2130,   275,   253, 18491,   313,    70,    15,
           72,   904, 12692,  7102,    13,  8990, 10097,    13, 13722,
          434,  7102,  6177,   187,   187,  4118, 37741,    27,    45,
         4988,    74,   556, 10097,   327, 27669, 11075,   264,    13,
         5271, 23058,    13, 19782, 37741, 10031,    13, 13814, 11397,
           13,   378, 16464,    13, 11759, 10535,  1981,    13, 21798,
        12989,    13,   285,   966, 10097,   327, 21708,    46, 10797,
         2130,   387,  5987,  1358,    77,  4988,    74,    14,  2284,
           15,  7280,    15,   900, 14206]])

In [229]:
#tokenize instruction dataset
def tokenize_function(examples):
    if "question" in examples and "answer" in examples:
      text = examples["question"][0] + examples["answer"][0]
    elif "input" in examples and "output" in examples:
      text = examples["input"][0] + examples["output"][0]
    else:
      text = examples["text"][0]

    tokenizer.pad_token = tokenizer.eos_token
    tokenized_inputs = tokenizer(
        text,
        return_tensors="np",
        padding=True,
    )

    max_length = min(
        tokenized_inputs["input_ids"].shape[1],
        2048
    )
    tokenizer.truncation_side = "left"
    tokenized_inputs = tokenizer(
        text,
        return_tensors="np",
        truncation=True,
        max_length=max_length
    )

    return tokenized_inputs

In [230]:
finetuning_dataset_loaded = datasets.load_dataset("json", data_files=filename, split="train")

tokenized_dataset = finetuning_dataset_loaded.map(
    tokenize_function,
    batched=True,
    batch_size=1,
    drop_last_batch=True
)

print(tokenized_dataset)

DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38068e00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b380911c0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'x-amz-id-2', b'nkomfrru73aD7s5DSydvvj017shgWuDMimyGHX/vT4cbJ6stNFQAJPKVgUqmG80tGnh25vIcAgs='), (b'x-amz-request-id', b'HS8DHA92C23C2QCN'), (b'Date', b'Sat, 08 Aug 2026 04:42:07 GMT'), (b'Last-Modified', b'Fri, 30 Oct 2020 13:23:58 GMT'), (b'ETag', b'"130c40bd983b7daceb51fa8ed06927f5"'), (b'x-amz-version-id', b'YQKJoZCytUl9DZHuRpAqYdO6daoK5oCc'), (b'Accept-Ranges', b'bytes'), (b'Content-Type', b'text/x-python'), (b'Content-Length', b'3635'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/json/json.py "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/json/default-85a40306d1d74f6a/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/json/default-85a40306d1d74f6a/0.0.0/f4e89e8750d5d5ffbef2c078bf0ddfedef29dc2faff52a6255cf513c05eb1092/dataset_info.json

Dataset({
    features: ['question', 'answer', 'input_ids', 'attention_mask'],
    num_rows: 1400
})

In [231]:
tokenized_dataset = tokenized_dataset.add_column("labels", tokenized_dataset["input_ids"])

In [232]:
#train,test splits
split_dataset = tokenized_dataset.train_test_split(test_size=0.1, shuffle=True, seed=123)
print(split_dataset)

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1260
    })
    test: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 140
    })
})

In [233]:
finetuning_dataset_path = "lamini/lamini_docs"
finetuning_dataset = datasets.load_dataset(finetuning_dataset_path)
print(finetuning_dataset)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38092fc0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b3806b320>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'249'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:18 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md?%2Fdatasets%2Flamini%2Flamini_docs%2Fresolve%2Fmain%2FREADME.md=&etag=%22e2ced51e1b668a09d8a4f5fa9cd381dacad5a754%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3aa-1ffa23fc36f202db3dbfb90d;c21203f2-a023-4288-a9e6-a7bb8df0acab'), (b'RateLimit', b'"resolvers";r=2999;t=290'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b's3APZCLLb7u3WQF954-ffIL_VG1R9fWWlf5TnOpb3fMx1w7YtveL9g==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'577'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 17:46:33 GMT'), (b'ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a722579-35c31b1c31dae84224fba867;69a45d97-fa66-4324-b301-48948aa806a3'), (b'RateLimit', b'"resolvers";r=2919;t=229'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'9NmpnkU2CuGYz-j2fkfXn3LtKDqFXaKBo0C8I35Ty5AdhP5oA6Y3TA=='), (b'Age', b'298545')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:18 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3aa-745f099c69be4b6874531adc;15627823-7ff3-435f-9d9b-8fed8726091c'), (b'RateLimit', b'"resolvers";r=2998;t=290'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ETU9RJC5oD-u6tKFuyQLmCOc9ZJXhDiq_0m7CFA0xTR98Sh5z1nHhg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b49ecd160>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2fe9cb30>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'KAQ0S4Z96DM4JWG1'), (b'x-amz-id-2', b'yRQ4/3jrN1w6W9QbRt/Nmxyisq4XauzM8ZTWplG0AGa6at4GJhU/R3RbFs2UBdEiCMHYyEwgN+I='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:42:17 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs/lamini/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:18 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3aa-66990dac0ea852c9258aedb9;3d336a45-268b-4b3d-a296-4bf13703cf3d'), (b'RateLimit', b'"resolvers";r=2997;t=290'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'W-1w6Tx04BGifEcQ6C9jO91kkGVdvaLV0Qn0CaXRyNf87EmzdJq0bw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='datasets-server.huggingface.co' port=443 local_address=None timeout=100.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b380826c0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='datasets-server.huggingface.co' timeout=100.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38082d80>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:18 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 9543852a33ab0793b0fff7e28c175f98.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'u85dW5j9UsPvNAGj3IjlNZ6vwLO011I3Cfzcq-bI2zJ47A66T9jvKw==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3aa-2f1321e74fe4a5d324d81230;b1faaf59-158a-4a35-ac37-dafed7ecd39f'), (b'RateLimit', b'"resolvers";r=2996;t=290'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BRQrsW8rJCVgW4g5_dJi9zf4OA1kVsDd_1RYwK_SbKCWvcZSmo4ffw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json

DatasetDict({
    train: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1260
    })
    test: Dataset({
        features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 140
    })
})

In [234]:
taylor_swift_dataset = "lamini/taylor_swift"
bts_dataset = "lamini/bts"
open_llms = "lamini/open_llms"

In [235]:
dataset_swiftie = datasets.load_dataset(taylor_swift_dataset)
print(dataset_swiftie["train"][1])

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'251'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/taylor_swift/8b30efae27d3168b883a2812e660f7728d62bee3/README.md?%2Fdatasets%2Flamini%2Ftaylor_swift%2Fresolve%2Fmain%2FREADME.md=&etag=%224079009b6e6a7e868aeafb630ef35178c99c9285%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ab-455c44492afa839825635749;bbe663cd-a4a0-47ba-8468-d132256f0ef9'), (b'RateLimit', b'"resolvers";r=2995;t=289'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"4079009b6e6a7e868aeafb630ef35178c99c9285"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'A6Kw90UwBCGxGXi9wxfUAfhLFbcEJXCFjq2UKE4j4efEoAysNwxrtg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/taylor_swift/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'573'), (b'Connection', b'keep-alive'), (b'Date', b'Fri, 07 Aug 2026 13:34:46 GMT'), (b'ETag', b'"4079009b6e6a7e868aeafb630ef35178c99c9285"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a75def6-3c522f856194030d481cb283;6110a355-cf21-4214-8d60-c22688b5b410'), (b'RateLimit', b'"resolvers";r=2994;t=26'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'OFZrPo4Ttes-GJDSLDe8HI4jCLUgOyyu9QqA84oiDNhWEplUap0gyQ=='), (b'Age', b'54453')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/taylor_swift/8b30efae27d3168b883a2812e660f7728d62bee3/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ab-49e970e173b2671c1f6df6b8;359f2a2a-596b-4671-af21-350f2a6f1043'), (b'RateLimit', b'"resolvers";r=2994;t=289'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'EFX7zbc2EHDkU5lypg2YbLK-OMXHebXcCdz6esxLqO9jmLr3gFITbg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/taylor_swift/resolve/8b30efae27d3168b883a2812e660f7728d62bee3/taylor_swift.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'QD5KE8JX6ZWEJ6PT'), (b'x-amz-id-2', b'1Glc5jrtzk0mjEgb5SUvfTsykiRNqMGmYbiF2757GdVITjCryeLrIKHRwk7EKAA+JD8FRLzrkHw='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:42:18 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/taylor_swift/lamini/taylor_swift.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ab-69a3c1e947e1b1be41e64dff;2e47025a-2744-4e6d-a57a-599e2304c0bb'), (b'RateLimit', b'"resolvers";r=2993;t=289'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'7JhnkAotzXSqVzrste4rf7qedaqyxJpqGL_i6iy-KF4SUfWZfeE-xQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/taylor_swift/resolve/8b30efae27d3168b883a2812e660f7728d62bee3/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 9543852a33ab0793b0fff7e28c175f98.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'1qPQOBh4gJPz_SabIjmRE8j0ZTwSbzjbZT7eSXwLSY_kYxhjUEq0BA==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/taylor_swift "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:19 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ab-0f4318cf4a36168f426c6095;eacb382f-ca54-487c-ac60-c4c47d1c274d'), (b'RateLimit', b'"resolvers";r=2992;t=289'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'8b30efae27d3168b883a2812e660f7728d62bee3'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 f31a6426ebd75ce4393909b12f5cbdcc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'3oSFwoQLUc6tDlJ2BGynznI0zoOHD7pXasPJH1yQv8bkWbOWbW0b3g==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/taylor_swift/resolve/8b30efae27d3168b883a2812e660f7728d62bee3/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___taylor_swift/default/0.0.0/8b30efae27d3168b883a2812e660f7728d62bee3/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___taylor_swift/default/0.0.0/8b30efae27d3168b883a2812e660f7728d62bee3/dataset_info.json

{'question': 'What is the most popular Taylor Swift song among millennials? How does this song relate to the millennial generation? What is the significance of this song in the millennial culture?', 'answer': 'Taylor Swift\'s "Shake It Off" is the most popular song among millennials. This song relates to the millennial generation as it is an anthem of self-acceptance and embracing one\'s individuality. The song\'s message of not letting others bring you down and to just dance it off resonates with the millennial culture, which is often characterized by a strong sense of individuality and a rejection of societal norms. Additionally, the song\'s upbeat and catchy melody makes it a perfect fit for the millennial generation, which is known for its love of pop music.', 'input_ids': [1276, 310, 253, 954, 4633, 11276, 24619, 4498, 2190, 24933, 8075, 32, 1359, 1057, 436, 4498, 14588, 281, 253, 24933, 451, 5978, 32, 1737, 310, 253, 8453, 273, 436, 4498, 275, 253, 24933, 451, 4466, 32, 37979, 24619, 434, 346, 2809, 640, 733, 5566, 3, 310, 253, 954, 4633, 4498, 2190, 24933, 8075, 15, 831, 4498, 7033, 281, 253, 24933, 451, 5978, 347, 352, 310, 271, 49689, 273, 1881, 14, 14764, 593, 285, 41859, 581, 434, 2060, 414, 15, 380, 4498, 434, 3935, 273, 417, 13872, 2571, 3324, 368, 1066, 285, 281, 816, 11012, 352, 745, 8146, 684, 342, 253, 24933, 451, 4466, 13, 534, 310, 2223, 7943, 407, 247, 2266, 3282, 273, 2060, 414, 285, 247, 18235, 273, 38058, 22429, 15, 9157, 13, 253, 4498, 434, 598, 19505, 285, 5834, 90, 40641, 2789, 352, 247, 3962, 4944, 323, 253, 24933, 451, 5978, 13, 534, 310, 1929, 323, 697, 2389, 273, 1684, 3440, 15], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'labels': [1276, 310, 253, 954, 4633, 11276, 24619, 4498, 2190, 24933, 8075, 32, 1359, 1057, 436, 4498, 14588, 281, 253, 24933, 451, 5978, 32, 1737, 310, 253, 8453, 273, 436, 4498, 275, 253, 24933, 451, 4466, 32, 37979, 24619, 434, 346, 2809, 640, 733, 5566, 3, 310, 253, 954, 4633, 4498, 2190, 24933, 8075, 15, 831, 4498, 7033, 281, 253, 24933, 451, 5978, 347, 352, 310, 271, 49689, 273, 1881, 14, 14764, 593, 285, 41859, 581, 434, 2060, 414, 15, 380, 4498, 434, 3935, 273, 417, 13872, 2571, 3324, 368, 1066, 285, 281, 816, 11012, 352, 745, 8146, 684, 342, 253, 24933, 451, 4466, 13, 534, 310, 2223, 7943, 407, 247, 2266, 3282, 273, 2060, 414, 285, 247, 18235, 273, 38058, 22429, 15, 9157, 13, 253, 4498, 434, 598, 19505, 285, 5834, 90, 40641, 2789, 352, 247, 3962, 4944, 323, 253, 24933, 451, 5978, 13, 534, 310, 1929, 323, 697, 2389, 273, 1684, 3440, 15]}

In [237]:
!pip install lamini

Requirement already satisfied: lamini in /usr/local/lib/python3.12/dist-packages (3.4.3)
Requirement already satisfied: lamini-configuration[yaml] in /usr/local/lib/python3.12/dist-packages (from lamini) (0.8.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from lamini) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from lamini) (4.67.3)
Requirement already satisfied: numpy<2.0.0 in /usr/local/lib/python3.12/dist-packages (from lamini) (1.26.4)
Requirement already satisfied: jsonlines in /usr/local/lib/python3.12/dist-packages (from lamini) (4.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from lamini) (2.2.2)
Requirement already satisfied: azure-storage-blob in /usr/local/lib/python3.12/dist-packages (from lamini) (12.30.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from lamini) (1.6.1)
Requirement already satisfied: sqlglot in /usr/local/lib/python3.12/dist-packages (from lamini) (25.20.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from lamini) (3.14.1)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (from lamini) (1.15.0)
Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (from lamini) (2.45.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (from lamini) (2.0.51)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from lamini) (8.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->lamini) (1.24.2)
Requirement already satisfied: azure-core>=1.37.0 in /usr/local/lib/python3.12/dist-packages (from azure-storage-blob->lamini) (1.41.0)
Requirement already satisfied: cryptography>=2.1.4 in /usr/local/lib/python3.12/dist-packages (from azure-storage-blob->lamini) (49.0.0)
Requirement already satisfied: isodate>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from azure-storage-blob->lamini) (0.7.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu->lamini) (26.2)
Requirement already satisfied: pyyaml<7.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from lamini-configuration[yaml]->lamini) (6.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (2.13.4)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai->lamini) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->lamini) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->lamini) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->lamini) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->lamini) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->lamini) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->lamini) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->lamini) (2026.6.17)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->lamini) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->lamini) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->lamini) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy->lamini) (3.5.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=2.1.4->azure-storage-blob->lamini) (2.1.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai->lamini) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->lamini) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->lamini) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->lamini) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai->lamini) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->lamini) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=2.1.4->azure-storage-blob->lamini) (3.0)

In [238]:
import datasets
import tempfile
import logging
import random
import config
import os
import yaml
import time
import torch
import transformers
import pandas as pd
import jsonlines

from utilities import *
from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM
from transformers import TrainingArguments
from transformers import AutoModelForCausalLM
from llama import BasicModelRunner



logger = logging.getLogger(__name__)
global_config = None

In [239]:
#loading lamini docs datasets
dataset_name = "lamini_docs.jsonl"
dataset_path = f"/content/{dataset_name}"
use_hf = False

In [240]:
dataset_path = "lamini/lamini_docs"
use_hf = True

In [241]:
model_name = "EleutherAI/pythia-70m"

In [296]:
# Keep an untouched copy of the pretrained model before training modifies it
pretrained_model = AutoModelForCausalLM.from_pretrained(model_name)
pretrained_model.to(device)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783c6db1e600>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2fe7f6e0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:12:30 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76babe-54eabe3e2aeb815a483b88bb;b2bc4edb-f354-4883-b00f-c7c2e5047663'), (b'RateLimit', b'"resolvers";r=2999;t=278'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BciMytAIXxnA56pqiK3TLLYQBeuTaA_NLhEKyie3E0XrCgYk_yAJIQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'dQcR8FMcsWxdYhQ7lXBcx8RlzS-Ash-SoCFxoxWZsYdilzTeS8-mDg=='), (b'Age', b'223772')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:12:31 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76babf-72781a28763a694803a0132e;4631f333-4187-494f-afec-4e51311289f0'), (b'RateLimit', b'"resolvers";r=2998;t=277'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'99HDeibe5nf2HCwMIjnOQHs_azzGse0T-KC8B08FnGJd_PFtaKbJ3Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ebnVcLPz7l_UQRTdARma3Ykkk90340rKY_hosLCDNXCvBnE9QB36jw=='), (b'Age', b'223772')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'282'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:12:31 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fgeneration_config.json=&etag=%22d1273fdfdec769418aa547e8e6f7174c523fed2f%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76babf-37ca093a0f85b932737e6ba6;12c340d3-247e-46cf-9031-311503644d7f'), (b'RateLimit', b'"resolvers";r=2997;t=277'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'cKPVlBpqomVRIPMb8nrC-kLLvmn1r7aGd_eWUHbJQO2ovmsGSbht_Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'111'), (b'Connection', b'keep-alive'), (b'Date', b'Mon, 03 Aug 2026 14:23:55 GMT'), (b'ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a70a47b-3268462d48af7e09781551ba;73a6a2d3-fc11-4f48-a8c5-801faa626ca1'), (b'RateLimit', b'"resolvers";r=2954;t=101'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 d59d2ab357c0c409dc4be130a9aab01e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'5569zQzCdwOSpd3qPLSuu8739JIya3nPAAUSjxvGkMicsROKk7fGDA=='), (b'Age', b'398916')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 512)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-5): 6 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXAttention(
          (query_key_value): Linear(in_features=512, out_features=1536, bias=True)
          (dense): Linear(in_features=512, out_features=512, bias=True)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): Linear(in_features=512, out_features=2048, bias=True)
          (dense_4h_to_h): Linear(in_features=2048, out_features=512, bias=True)
          (act): GELUActivation()
        )
      )
    )
    (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): GPTNeoXRotaryEmbedding()
  )
  (embed_out): Linear(in_features=512, out_features=50304, bias=False)
)

In [242]:
training_config = {
    "model": {
        "pretrained_name": model_name,
        "max_length" : 2048
    },
    "datasets": {
        "use_hf": use_hf,
        "path": dataset_path
    },
    "verbose": True
}

In [243]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
train_dataset, test_dataset = tokenize_and_split_data(training_config, tokenizer)

print(train_dataset)
print(test_dataset)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8af01790>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8af03680>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:30 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b6-795debce65f51adb65b0539c;b432b831-f780-48f4-b3fd-7ac4f559ae33'), (b'RateLimit', b'"resolvers";r=2991;t=278'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'gLlUkEvYNz1A1Hyj_nUaj6nv2KUX9N-RXXbD1dcMQjsLN2dZSN8b-Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'gFbnBSn_pknysAci0KKnbdAZ-ep1Kbhh2R8V4NNrfrx5OAUbr85dJw=='), (b'Age', b'3849071')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'266'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:30 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22f1860edb10f80bcaf7b023fce47c68a23b724c23%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b6-0005d2725035c3f76959eac1;f13b0ee3-4af5-4929-b83a-a68b9400dd3d'), (b'RateLimit', b'"resolvers";r=2990;t=278'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'vcL-QrgkuiJFPvwe6dnxIltF7uwFR7tJbCUK64zBQbqPZqpQ0nZaXw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'396'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 25 Nov 2025 07:32:47 GMT'), (b'ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69255b9f-43c8b47b06ae4d4b7a5b6850;d0cf6526-71cd-486d-ab80-dbe3d2f787dd'), (b'RateLimit', b'"resolvers";r=2888;t=21'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'lheVhMezRHdw_aFgCmPXghL8RBqipxgEe1MlLEBxbRDJQAGlL3bDhQ=='), (b'Age', b'22108183')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:30 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b6-354a7bb05cf9b6d77143765a;3e4dd69a-0601-47d5-8367-b84f61110c0c'), (b'RateLimit', b'"api";r=499;t=278'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'92d_QlKACzuIZ-Gau4XOwEY993Rd8CvbQpeBHbHyXs_caKyvhwELIw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:31 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"4c3-dou0MC1Uk5uul8iexhdohgHrzho"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b7-173b2ff8521462565183ce3d;5ccc70b3-9df0-4fba-bf4c-b1b920a2f096'), (b'RateLimit', b'"api";r=498;t=277'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'hyxlmaSGYsgQhq62o9qV5paOorQ3i_9AgQd7Pl26Cl4AOU-TDGTRPQ==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:utilities:Config: datasets.path: lamini/lamini_docs
datasets.use_hf: true
model.max_length: 2048
model.pretrained_name: EleutherAI/pythia-70m
verbose: true

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'249'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:31 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md?%2Fdatasets%2Flamini%2Flamini_docs%2Fresolve%2Fmain%2FREADME.md=&etag=%22e2ced51e1b668a09d8a4f5fa9cd381dacad5a754%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b7-2e5f47c21c382a98130ee75c;9d464455-eb0e-4c0c-aa7e-371463185b27'), (b'RateLimit', b'"resolvers";r=2989;t=277'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'Wcd8FG9eH6FGRbV4Q1jp4ACaCap2fQMBcUVjefn44Si33Vo4CPJiXA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'577'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 17:46:33 GMT'), (b'ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a722579-35c31b1c31dae84224fba867;69a45d97-fa66-4324-b301-48948aa806a3'), (b'RateLimit', b'"resolvers";r=2919;t=229'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'Zz7sZrq3U8KS2dJttSVy8ModT7PA46TGidF29AHmumhJIDYLVhQikw=='), (b'Age', b'298558')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete

tokenize True lamini/lamini_docs

DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8bee9f40>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b6de50230>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'NQNP4P51FRRGBQGP'), (b'x-amz-id-2', b'ZA4kj60rW/vjyi6BI479JTlsuIhaaVR9I/yjbdCbVZnUzLGjMBt2Q9VmQ8iIyg9luF6pQa3X0CY='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:42:31 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs/lamini/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:31 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b7-45e902f209e4a50a163db017;681e434b-05b5-40a5-9558-f2b5ecdaf956'), (b'RateLimit', b'"resolvers";r=2987;t=277'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'FL2OKHEqN-c5NBjp86E2kdSbfYD5lnkiycJNx1XcpHFORfVTfe42lw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='datasets-server.huggingface.co' port=443 local_address=None timeout=100.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8beebc50>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='datasets-server.huggingface.co' timeout=100.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8beebad0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:31 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 1ddd3ba3dd9b9f41f86c2ea1807f3f4e.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'Pp-Yp9MyFa5_I7azSi1GV07t5XvxgD_u9mzMD5sGaEcdZ_LH5izKKQ==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:32 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b8-37518658215132da4215865d;bc38ab70-bfe6-41aa-8623-0defd2531ac9'), (b'RateLimit', b'"resolvers";r=2986;t=276'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'5QtjIcpi_MjRZGXMoSFjTDnrIZSepOx5craIsP50cUQ_dRO4dnzGpA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json

Dataset({
    features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 1260
})
Dataset({
    features: ['question', 'answer', 'input_ids', 'attention_mask', 'labels'],
    num_rows: 140
})

In [244]:
#loading base model
base_model = AutoModelForCausalLM.from_pretrained(model_name)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:32 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b8-6b78d0df5160a1706f76bbd9;8802daa6-cfb8-4f81-9332-a58b3288f68d'), (b'RateLimit', b'"resolvers";r=2985;t=276'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'-c6sG27wtoUy6REs7uujyMg_NbAC6d7Y95CczG1XrusuYcsiyjG3XQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'SyeerRs1seRfENWFdRA8f2uQ0ewzhpMBzziid7Ve9_5J50tynrY1Xg=='), (b'Age', b'3849073')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:32 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b8-712a69327434928571cba0e3;7d14e05d-1d8f-4942-9670-76bffa0f57ed'), (b'RateLimit', b'"resolvers";r=2984;t=276'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'uCIP9IBOVCDH0ivltCYmT3hrv3q0f_XTjy154D1G6MG6jorNnHQe-Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'KokQqbj7zVv2Tm5xrlRP_aV4hUTQbZioQILMEJGPgaFkUIpXlHA_-Q=='), (b'Age', b'3849073')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:32 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b8-00a78aec26a4ad617bea1955;e7e82684-e077-4d01-9f17-291ffd108982'), (b'RateLimit', b'"resolvers";r=2983;t=276'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'lt8GLjywHNinf0jMOazY3GZAwWxEoIDk96oUgiOqicg0DmiCg8-LVw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:33 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3b9-4feabf6376def3ef5152a407;9094488e-1ea2-4439-9d4b-bcaf9c3291f0'), (b'RateLimit', b'"resolvers";r=2982;t=275'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'P0fl-fIQNFsFDcepHBksfdxwcvZ-_F8gV9Jt137bX9Y_vzAPaZS-eQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'No_PjJ735AzgdNQ9LAU4XAMhXJo-Hz64s1N2-yMtmFPa71-CT4-OKg=='), (b'Age', b'3849074')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [245]:
device_count = torch.cuda.device_count()
if device_count > 0:
    logger.debug("Select GPU device")
    device = torch.device("cuda")
else:
    logger.debug("Select CPU device")
    device = torch.device("cpu")

DEBUG:__main__:Select GPU device

In [246]:
base_model.to(device)

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 512)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-5): 6 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXAttention(
          (query_key_value): Linear(in_features=512, out_features=1536, bias=True)
          (dense): Linear(in_features=512, out_features=512, bias=True)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): Linear(in_features=512, out_features=2048, bias=True)
          (dense_4h_to_h): Linear(in_features=2048, out_features=512, bias=True)
          (act): GELUActivation()
        )
      )
    )
    (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): GPTNeoXRotaryEmbedding()
  )
  (embed_out): Linear(in_features=512, out_features=50304, bias=False)
)

In [247]:
#function to carry out interface
def inference(text, model, tokenizer, max_input_tokens=1000, max_output_tokens=100):
  # Tokenize
  input_ids = tokenizer.encode(
          text,
          return_tensors="pt",
          truncation=True,
          max_length=max_input_tokens
  )

  # Generate
  device = model.device
  generated_tokens_with_prompt = model.generate(
    input_ids=input_ids.to(device),
    max_length=max_output_tokens
  )

  # Decode
  generated_text_with_prompt = tokenizer.batch_decode(generated_tokens_with_prompt, skip_special_tokens=True)

  # Strip the prompt
  generated_text_answer = generated_text_with_prompt[0][len(text):]

  return generated_text_answer

In [248]:
#try base model
test_text = test_dataset[0]['question']
print("Question input (test):", test_text)
print(f"Correct answer from Lamini docs: {test_dataset[0]['answer']}")
print("Model's answer: ")
print(inference(test_text, base_model, tokenizer))

Question input (test): Can Lamini generate technical documentation or user manuals for software projects?
Correct answer from Lamini docs: Yes, Lamini can generate technical documentation and user manuals for software projects. It uses natural language generation techniques to create clear and concise documentation that is easy to understand for both technical and non-technical users. This can save developers a significant amount of time and effort in creating documentation, allowing them to focus on other aspects of their projects.
Model's answer:


A:

I think the answer is to use a "manual" of the "manual" of the software.

A:

I think the answer is to use a "manual" of the software.

A:

I think the answer is to use a "manual" of the software.

A:

I think the answer is to use a "manual"

In [249]:
#stepup training
max_steps = 3

In [250]:
trained_model_name = f"lamini_docs_{max_steps}_steps"
output_dir = trained_model_name

In [251]:
training_args = TrainingArguments(

    # Learning rate
    learning_rate=1.0e-5,

    # Number of training epochs
    num_train_epochs=1,

    # Max steps to train for
    # Overrides num_train_epochs if not -1
    max_steps=max_steps,

    # Batch size for training
    per_device_train_batch_size=1,

    # Directory to save model checkpoints
    output_dir=output_dir,

    # Other arguments
    disable_tqdm=False,

    # Evaluation
    eval_steps=120,

    # Checkpoint saving
    save_steps=120,

    # Learning-rate warmup
    warmup_steps=1,

    # Evaluation batch size
    per_device_eval_batch_size=1,

    # Transformers 5.x uses eval_strategy
    eval_strategy="steps",

    # Logging
    logging_strategy="steps",
    logging_steps=1,

    # Optimizer
    optim="adafactor",

    # Gradient accumulation
    gradient_accumulation_steps=4,

    # Gradient checkpointing
    gradient_checkpointing=False,

    # Best-model selection
    load_best_model_at_end=True,
    save_total_limit=1,
    metric_for_best_model="eval_loss",
    greater_is_better=False
)

In [252]:
print(base_model)

print(
    "Memory footprint:",
    base_model.get_memory_footprint() / 1e9,
    "GB"
)

print("FLOPs calculation skipped because floating_point_ops() "
      "is not available in this Transformers version.")

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 512)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-5): 6 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXAttention(
          (query_key_value): Linear(in_features=512, out_features=1536, bias=True)
          (dense): Linear(in_features=512, out_features=512, bias=True)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): Linear(in_features=512, out_features=2048, bias=True)
          (dense_4h_to_h): Linear(in_features=2048, out_features=512, bias=True)
          (act): GELUActivation()
        )
      )
    )
    (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): GPTNeoXRotaryEmbedding()
  )
  (embed_out): Linear(in_features=512, out_features=50304, bias=False)
)
Memory footprint: 0.140853312 GB
FLOPs calculation skipped because floating_point_ops() is not available in this Transformers version.

In [253]:
from transformers import Trainer

trainer = Trainer(
    model=base_model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    callbacks=[]
)

trainer.do_grad_scaling = False

In [254]:
#train a few steps
training_output = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [255]:
#saving model locally
save_dir = f'{output_dir}/final'

trainer.save_model(save_dir)
print("Saved model to:", save_dir)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved model to: lamini_docs_3_steps/final

In [256]:
finetuned_slightly_model = AutoModelForCausalLM.from_pretrained(save_dir, local_files_only=True)

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

In [257]:
finetuned_slightly_model.to(device)

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 512)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-5): 6 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXAttention(
          (query_key_value): Linear(in_features=512, out_features=1536, bias=True)
          (dense): Linear(in_features=512, out_features=512, bias=True)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): Linear(in_features=512, out_features=2048, bias=True)
          (dense_4h_to_h): Linear(in_features=2048, out_features=512, bias=True)
          (act): GELUActivation()
        )
      )
    )
    (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): GPTNeoXRotaryEmbedding()
  )
  (embed_out): Linear(in_features=512, out_features=50304, bias=False)
)

In [258]:
#running slightly different model
test_question = test_dataset[0]['question']
print("Question input (test):", test_question)

print("Finetuned slightly model's answer: ")
print(inference(test_question, finetuned_slightly_model, tokenizer))

Question input (test): Can Lamini generate technical documentation or user manuals for software projects?
Finetuned slightly model's answer:


I have a question for the first time, and I have a question for the second time, and I have a question for the third time, and I have a question for the fourth time, and I have a question for the fourth time, and I have a question for the fourth time, and I have a question for the fourth time, and I have a question for the fourth time, and I have a

In [259]:
test_answer = test_dataset[0]['answer']
print("Target answer output (test):", test_answer)

Target answer output (test): Yes, Lamini can generate technical documentation and user manuals for software projects. It uses natural language generation techniques to create clear and concise documentation that is easy to understand for both technical and non-technical users. This can save developers a significant amount of time and effort in creating documentation, allowing them to focus on other aspects of their projects.

In [297]:
# Real finetuned model (fully trained by Lamini team)
finetuned_longer_model = AutoModelForCausalLM.from_pretrained("lamini/lamini_docs_finetuned")
tokenizer = AutoTokenizer.from_pretrained("lamini/lamini_docs_finetuned")
finetuned_longer_model.to(device)

print("=== PRETRAINED (pretrained_model) ===")
print(inference(test_question, pretrained_model, tokenizer))

print("\n=== FINETUNED (finetuned_longer_model) ===")
print(inference(test_question, finetuned_longer_model, tokenizer))

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38092fc0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b38083260>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:25 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf5-006895382b02ada811201407;5636fada-7219-42e2-9ff8-daabbb2c904a'), (b'RateLimit', b'"resolvers";r=2996;t=223'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'R0dwzc9OgBbXz9W-muxFBlMO0XYbpk9B88e8nlo6o2m79-toIFQF_w==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'NDR4Nbuu8PjSIMzEUJPz04J2lgbn8vpuP4VHAIR25Sq2TxW_WCN0uQ=='), (b'Age', b'223826')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:25 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf5-40118dcf603706334373ba15;96e8ff8f-9c75-437b-aed4-15234128e9ce'), (b'RateLimit', b'"resolvers";r=2995;t=223'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'lPGtaIiOXhGkdvQ4RFBv3N0lom71Fc0cOSCoqyKgsyCo8TvKDAtH0Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'0LdbBXs5xNvop8ZKm5sc3qCY_E2yoI8YePBNBwu2BOPfIOOTqmWcqw=='), (b'Age', b'223826')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'282'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:26 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fgeneration_config.json=&etag=%22d1273fdfdec769418aa547e8e6f7174c523fed2f%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf5-256bb9317030521e22c5eb68;2a500dcd-aeec-464b-bd53-910749c88307'), (b'RateLimit', b'"resolvers";r=2994;t=223'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'cVYgfy5TXNEoDvCVeRDgORPWXHd0lMsF71luh8HDw312NAYdceglQA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'111'), (b'Connection', b'keep-alive'), (b'Date', b'Mon, 03 Aug 2026 14:23:55 GMT'), (b'ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a70a47b-3268462d48af7e09781551ba;73a6a2d3-fc11-4f48-a8c5-801faa626ca1'), (b'RateLimit', b'"resolvers";r=2954;t=101'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'j9Bv311VWgb_45L20uFayEXGa6AzJBTYB-Wb8KU3X6gHdSidcrlXjQ=='), (b'Age', b'398971')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:26 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf6-7655f2f73a3a1000712bba7e;1b9a4887-c388-463b-bbc6-eedf37a718cd'), (b'RateLimit', b'"resolvers";r=2993;t=222'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'a7nMwBbuAliB3zFrq0bX914XSx7an9ItOr7vG5co5FgNsObQN7PJnQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'VOSQAQyVqPLhEJ43xjSdJEKvzOP2aw1HlkjmvsX72SUVLbnrmNIxxQ=='), (b'Age', b'223827')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'280'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:26 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/tokenizer_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22c0d792bfdf7eead80999b587a412553ebac8521b%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf6-0b6b9878712ec20976bea1d2;34b30707-ff7f-4273-8faa-0dca5e569b19'), (b'RateLimit', b'"resolvers";r=2992;t=222'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"c0d792bfdf7eead80999b587a412553ebac8521b"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'3JcC4xnDLfd9STCoefObp7GPif5lIr-wN83p-hBLi5xhb_HtNL0UXA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'264'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 07:56:56 GMT'), (b'ETag', b'"c0d792bfdf7eead80999b587a412553ebac8521b"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a719b48-18ff09dd20350e787b5c744b;af440756-a97a-4539-be97-9f5458563581'), (b'RateLimit', b'"resolvers";r=2992;t=220'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'SaOTPdpNKpCoJXTH9okSExpUYBFpp7Sr7mgspUhG_wY0n1UrYpMP_g=='), (b'Age', b'335790')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:26 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf6-33da8792567a4a5565b21bd7;4279cd68-944c-459e-b1ee-cbd08e24b8a6'), (b'RateLimit', b'"api";r=499;t=222'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'7HSU43jR5ruQwTLJ2PBRRnSkTb7rFdlWtdNh4IwN1AAL-5_lQ8B8Ow==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/lamini/lamini_docs_finetuned/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 05:13:26 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"651-csfkDo17onY4xklmhljuXTbJpQE"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76baf6-277ec5b558144eb156d50e81;a22c23c9-60f0-4bbe-a72d-ef9346e1021d'), (b'RateLimit', b'"api";r=498;t=222'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 b5afed9af6ab9ac8245e8872d677a7bc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'fCORYJumVbKu5FrFDdSmb3PPntTnbvdP_Vao_RKpo0KbW1vOez6mHA==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/lamini/lamini_docs_finetuned/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

=== PRETRAINED (pretrained_model) ===
Yes, Lamini can generate technical documentation or user manuals for software projects. This can be achieved by providing a prompt for a specific technical question or question to the LLM Engine, or by providing a prompt for a specific technical question or question. Additionally, Lamini can be trained on specific technical questions or questions to help users understand the process and provide feedback to the LLM Engine. Additionally, Lamini

=== FINETUNED (finetuned_longer_model) ===
Yes, Lamini can generate technical documentation or user manuals for software projects. This can be achieved by providing a prompt for a specific technical question or question to the LLM Engine, or by providing a prompt for a specific technical question or question. Additionally, Lamini can be trained on specific technical questions or questions to help users understand the process and provide feedback to the LLM Engine. Additionally, Lamini

In [261]:
#exploring moderation using small model
base_tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-70m")
base_model = AutoModelForCausalLM.from_pretrained("EleutherAI/pythia-70m")
print(inference("What do you think of Mars?", base_model, base_tokenizer))

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:41 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c1-6034d3875497c2077cc557c7;28682fcd-9e57-4f05-ac49-99c8aed3708e'), (b'RateLimit', b'"resolvers";r=2976;t=267'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'HIT'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'AW9yzNfdiAgRs2pzVO9t9XDgSQx3kfKDbuUQVXIGTVo-VPh-YS1FeQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'hKrE-RyTZ-BbFcFHWkhKPmbTIruG60hPmpRaicNcNQ0gc4QNECBhVA=='), (b'Age', b'3849082')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'266'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:42 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22f1860edb10f80bcaf7b023fce47c68a23b724c23%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c2-4addb4c75294853a2270e80c;8e10fa64-c2d9-4bf6-9319-90ee82de3fb1'), (b'RateLimit', b'"resolvers";r=2975;t=266'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'8ZQwwl3rm1QXAUZK_MJ9O7bTQsxL0PHC8_ZizEY2IO3RMdnjSdUGjQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'396'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 25 Nov 2025 07:32:47 GMT'), (b'ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-69255b9f-43c8b47b06ae4d4b7a5b6850;d0cf6526-71cd-486d-ab80-dbe3d2f787dd'), (b'RateLimit', b'"resolvers";r=2888;t=21'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'IKQn-Xfw4h5r4_tC2pT79zW58m_KIgKkH8ynSWtNf1dV5cnpncBH9A=='), (b'Age', b'22108195')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:42 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c2-49fc4e915ebb5c85566ce6e7;03506f7e-c157-47d6-937b-40f2ebf14a83'), (b'RateLimit', b'"api";r=495;t=266'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'iz2FlhsBf9MWgBAaAq6oMcGhoMQe-JFldXZazBCmIy4afF6cAG1BNQ==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:42 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"4c3-dou0MC1Uk5uul8iexhdohgHrzho"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c2-5f428b58457d1f3f2c665ed8;cf36f74d-42d5-4095-9682-cdfcbe20f699'), (b'RateLimit', b'"api";r=494;t=266'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'5qimMCT4ftk4KbsP_TCHJQhUdme2Ny8eLHk7lCTlirsf9E1i1quoZg==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-70m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:42 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c2-1b5533063413d52c21d4a2f0;4ce77d86-90f7-4ff9-9acc-94ca423a81b0'), (b'RateLimit', b'"resolvers";r=2999;t=266'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'OHxj_DvftGH_96pScw47i7dje6Go-8zLFwv2AG9vjbcvI2GeGZWnHA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BRxvgmwhBgWs3TO2Ue5KvTcdQzX78AhxanrNbwb89Mp65nwAycdasw=='), (b'Age', b'3849084')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:43 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c3-643a50334f6b342a73dc0ecd;08eb444e-5f39-4586-9f24-d3ae7b0def0d'), (b'RateLimit', b'"resolvers";r=2972;t=265'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'JJDCmhZJ7vIdJMEp2SE6quNmRiJIlrDwoGyQxj7K6WRG59KFlRcc0w==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/generation_config.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'246'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:43 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json?%2FEleutherAI%2Fpythia-70m%2Fresolve%2Fmain%2Fconfig.json=&etag=%22d7a9196e329eaf06d6e2802fed376e7459834236%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c3-5a36ca3e1faa08067d753ed8;15cdd3db-4433-4acf-a912-bdb219601953'), (b'RateLimit', b'"resolvers";r=2971;t=265'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'rX-OIECZS_imSnKVUfxiKw-kwISk9b1dFxGS4SnKuUah_5R4Pdnuzw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-70m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'567'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 24 Jun 2026 15:31:19 GMT'), (b'ETag', b'"d7a9196e329eaf06d6e2802fed376e7459834236"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a3bf847-03931e6043d603794ca8ca5b;5b1bacaa-a464-4a26-b4b6-2bba9a9065d8'), (b'RateLimit', b'"resolvers";r=2999;t=209'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'a39f36b100fe8a5377810d56c3f4789b9c53ac42'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'H7600xLicbKAuAkSAT4P6YecgXv5EsNDVbWbIVRunmNrtw3t6MIFaA=='), (b'Age', b'3849084')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-70m/a39f36b100fe8a5377810d56c3f4789b9c53ac42/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

I think I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I’m going to go to Mars.

I

In [262]:
print(inference("What do you think of Mars?", finetuned_longer_model, tokenizer))

Let’s keep the discussion relevant to Lamini. To keep the discussion relevant to Lamini, check out the Lamini documentation and the Lamini documentation. For more information, visit https://lamini-ai.github.io/Lamini/. For more information, visit https://lamini-ai.github.io/. For more information, visit https://lamini-ai.github.io/. For more

In [263]:
import datasets
import tempfile
import logging
import random
import config
import os
import yaml
import logging
import difflib
import pandas as pd

import transformers
import datasets
import torch

from tqdm import tqdm
from utilities import *
from transformers import AutoTokenizer, AutoModelForCausalLM

logger = logging.getLogger(__name__)
global_config = None

In [264]:
dataset = datasets.load_dataset("lamini/lamini_docs")

test_dataset = dataset["test"]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'249'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:48 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md?%2Fdatasets%2Flamini%2Flamini_docs%2Fresolve%2Fmain%2FREADME.md=&etag=%22e2ced51e1b668a09d8a4f5fa9cd381dacad5a754%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c8-2d572b75682b58307d642c18;335ca9fd-468f-42c7-b959-dffb1922f019'), (b'RateLimit', b'"resolvers";r=2970;t=260'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'2tqNOtDSGxQC7Ivvq3XR7cJw4_nQghGvhiHZUsk0Ij6CzctFL61ecg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'577'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 17:46:33 GMT'), (b'ETag', b'"e2ced51e1b668a09d8a4f5fa9cd381dacad5a754"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a722579-35c31b1c31dae84224fba867;69a45d97-fa66-4324-b301-48948aa806a3'), (b'RateLimit', b'"resolvers";r=2919;t=229'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'5dYevbCV56bQj5PjQbrgZxmjvuB1S6SWSBiefLuptR1J7RyfKFOLTA=='), (b'Age', b'298575')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs/05bd680b81d69a7a1d38193873f1487d73e535bf/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:48 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c8-7a2e4e1d78b22e1f2cf10b92;8d8c7e3a-0da1-447c-9789-d9b6cc654a6d'), (b'RateLimit', b'"resolvers";r=2969;t=260'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'YjJfgcimDMVNKUSkrMHqm1CKkpEnbbTs65yLxiHNrTob4IV8uAvFwg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b4facef00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b49eb7500>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'HT62G1QKG13E9FYD'), (b'x-amz-id-2', b'pDvMZhhfcsQZzMK3so9VnGPGsxOxc4ZmeSTI0Fswfc0A6NN6GcgH5DZZrtHDK/xnAUbUrImhdlrwyqF5JTJRZdAMQvHrvHSF'), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:42:48 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs/lamini/lamini_docs.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:48 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c8-718fc2995bab1d3764a3574e;712d9f6f-b8b8-4759-aca6-58a3111603a8'), (b'RateLimit', b'"resolvers";r=2968;t=260'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'e3LZ07ulaSMPoKXgsWTgX3kwKW_4sUc8GqVQz29IFzVQDb7sxoOGNg==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='datasets-server.huggingface.co' port=443 local_address=None timeout=100.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8ae04bc0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='datasets-server.huggingface.co' timeout=100.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8ae04950>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:48 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 da0ff46c89069bb94e41a111871964ae.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'0inByjhqrnGbnJhB4-kHNS8KZIYyMJiJdpIXjQz9xBJBSur5ZnDanw==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:49 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c9-212d2f141d351495715be081;05d3e129-0b5f-4ec7-bbc0-49eb55a85756'), (b'RateLimit', b'"resolvers";r=2967;t=259'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'05bd680b81d69a7a1d38193873f1487d73e535bf'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'QbDk4Fl5ucDiTwum78EQfAkKiw47GM3BLlGX0AT5M0LVgmWJ5jqp3Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs/resolve/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs/default/0.0.0/05bd680b81d69a7a1d38193873f1487d73e535bf/dataset_info.json

In [265]:
print(test_dataset[0]["question"])
print(test_dataset[0]["answer"])

Can Lamini generate technical documentation or user manuals for software projects?
Yes, Lamini can generate technical documentation and user manuals for software projects. It uses natural language generation techniques to create clear and concise documentation that is easy to understand for both technical and non-technical users. This can save developers a significant amount of time and effort in creating documentation, allowing them to focus on other aspects of their projects.

In [266]:
model_name = "lamini/lamini_docs_finetuned"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:49 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c9-0ce86f44191c911c60d86af1;443f8bff-7724-43f4-b372-eb10e0c4e90f'), (b'RateLimit', b'"resolvers";r=2966;t=259'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ONBAQ7IIhfpwD4HUDYNVrAJZ1XcBmHC87FUx75xOC51ZiKx6BFqaNw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'e0mzgBEFTUlEewPpBwwJeAkXcmrf4xYJ1L8VwMuLcKGd534gLPn--A=='), (b'Age', b'221990')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'280'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:49 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/tokenizer_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22c0d792bfdf7eead80999b587a412553ebac8521b%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c9-5b12e02620adf37a2e39075d;1e26f5e6-f672-42a2-9aa2-7e52e8f23960'), (b'RateLimit', b'"resolvers";r=2965;t=259'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"c0d792bfdf7eead80999b587a412553ebac8521b"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'7C7aKa4vnbt3dSntkcGlCIUZQ5T7eeIJHgejDQK6S4zyDy25TokfGA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'264'), (b'Connection', b'keep-alive'), (b'Date', b'Tue, 04 Aug 2026 07:56:56 GMT'), (b'ETag', b'"c0d792bfdf7eead80999b587a412553ebac8521b"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a719b48-18ff09dd20350e787b5c744b;af440756-a97a-4539-be97-9f5458563581'), (b'RateLimit', b'"resolvers";r=2992;t=220'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'lvEBwQl16cAGYFaYsAg5QpKA2e1nNvmFoGA_Y681YSY4gSO3aIrmew=='), (b'Age', b'333953')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:49 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c9-4dc240b27b14a21d35df3be0;e92393b8-1260-4fcd-b53f-1c6ff144061a'), (b'RateLimit', b'"api";r=493;t=259'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'vHpCgoB8sG8YL3xoPUzR0Oxw7F0ko2bbLMU1ZlpugJ1t32Pzg7aLxw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/lamini/lamini_docs_finetuned/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:49 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"651-csfkDo17onY4xklmhljuXTbJpQE"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3c9-003f45d738d50ebf026f0f1c;d6e25439-3f91-401d-a07d-90f110c2e6ee'), (b'RateLimit', b'"api";r=492;t=259'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'1AYPzhylHKTHBZO8lH5tI1__SftltRpNvQPxK8UagPxdUyOP6En0Dg==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/lamini/lamini_docs_finetuned/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'260'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:50 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fconfig.json=&etag=%220b6a66001f78ae2af82b49afc6efd0ac7279e42a%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ca-1b7b5cf26fc8522e0a63b9ef;3c5c790d-8177-432d-8fff-1e710f7297e7'), (b'RateLimit', b'"resolvers";r=2964;t=258'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'SIGL8wC_wkKh1v8pzGtClu58RVc5423b3LSIgVa-ubyzgrmj4bTgrw==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'717'), (b'Connection', b'keep-alive'), (b'Date', b'Wed, 05 Aug 2026 15:02:59 GMT'), (b'ETag', b'"0b6a66001f78ae2af82b49afc6efd0ac7279e42a"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a7350a3-18be9cbe55a4e18364293378;243e074f-5ecc-4e01-8682-74774f0dd967'), (b'RateLimit', b'"resolvers";r=2951;t=157'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'ntt9HpTfuVxfpxPQCYZbcssQQEBt9hMwPvIRtHwYwwh_Y1mePHWfzw=='), (b'Age', b'221991')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'282'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:42:50 GMT'), (b'Location', b'/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json?%2Flamini%2Flamini_docs_finetuned%2Fresolve%2Fmain%2Fgeneration_config.json=&etag=%22d1273fdfdec769418aa547e8e6f7174c523fed2f%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3ca-1a2672a34a630f8a024af7ec;d2ecad07-455e-41dd-8f34-b171e6435109'), (b'RateLimit', b'"resolvers";r=2962;t=258'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'wGepqXllPE9vR7D_XeV5NdZIlFQmg2It5odoVeoprIkr9-J3XCKj4g==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/lamini/lamini_docs_finetuned/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'111'), (b'Connection', b'keep-alive'), (b'Date', b'Mon, 03 Aug 2026 14:23:55 GMT'), (b'ETag', b'"d1273fdfdec769418aa547e8e6f7174c523fed2f"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a70a47b-3268462d48af7e09781551ba;73a6a2d3-fc11-4f48-a8c5-801faa626ca1'), (b'RateLimit', b'"resolvers";r=2954;t=101'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'generation_config.json; filename="generation_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e03197159f8aaf8b951ead0d21237556.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'jQyM7j3bstGhQVlh4XzRygZiuboRI9Qd_BZVdnNWMWo523_VrPCZFQ=='), (b'Age', b'397135')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/lamini/lamini_docs_finetuned/7fb0b3eb43736cfd3db4a8baaf43ae73ec93f922/generation_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

In [267]:
def is_exact_match(a, b):
    return a.strip() == b.strip()

In [268]:
model.eval()

GPTNeoXForCausalLM(
  (gpt_neox): GPTNeoXModel(
    (embed_in): Embedding(50304, 512)
    (emb_dropout): Dropout(p=0.0, inplace=False)
    (layers): ModuleList(
      (0-5): 6 x GPTNeoXLayer(
        (input_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_layernorm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (post_attention_dropout): Dropout(p=0.0, inplace=False)
        (post_mlp_dropout): Dropout(p=0.0, inplace=False)
        (attention): GPTNeoXAttention(
          (query_key_value): Linear(in_features=512, out_features=1536, bias=True)
          (dense): Linear(in_features=512, out_features=512, bias=True)
        )
        (mlp): GPTNeoXMLP(
          (dense_h_to_4h): Linear(in_features=512, out_features=2048, bias=True)
          (dense_4h_to_h): Linear(in_features=2048, out_features=512, bias=True)
          (act): GELUActivation()
        )
      )
    )
    (final_layer_norm): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): GPTNeoXRotaryEmbedding()
  )
  (embed_out): Linear(in_features=512, out_features=50304, bias=False)
)

In [269]:
def inference(text, model, tokenizer, max_input_tokens=1000, max_output_tokens=100):
  # Tokenize
  tokenizer.pad_token = tokenizer.eos_token
  input_ids = tokenizer.encode(
      text,
      return_tensors="pt",
      truncation=True,
      max_length=max_input_tokens
  )

  # Generate
  device = model.device
  generated_tokens_with_prompt = model.generate(
    input_ids=input_ids.to(device),
    max_length=max_output_tokens
  )

  # Decode
  generated_text_with_prompt = tokenizer.batch_decode(generated_tokens_with_prompt, skip_special_tokens=True)

  # Strip the prompt
  generated_text_answer = generated_text_with_prompt[0][len(text):]

  return generated_text_answer

In [270]:
test_question = test_dataset[0]["question"]
generated_answer = inference(test_question, model, tokenizer)
print(test_question)
print(generated_answer)

Can Lamini generate technical documentation or user manuals for software projects?
Yes, Lamini can generate technical documentation or user manuals for software projects. This can be achieved by providing a prompt for a specific technical question or question to the LLM Engine, or by providing a prompt for a specific technical question or question. Additionally, Lamini can be trained on specific technical questions or questions to help users understand the process and provide feedback to the LLM Engine. Additionally, Lamini

In [271]:
answer = test_dataset[0]["answer"]
print(answer)

Yes, Lamini can generate technical documentation and user manuals for software projects. It uses natural language generation techniques to create clear and concise documentation that is easy to understand for both technical and non-technical users. This can save developers a significant amount of time and effort in creating documentation, allowing them to focus on other aspects of their projects.

In [272]:
exact_match = is_exact_match(generated_answer, answer)
print(exact_match)

False

In [298]:
n = 10
results = {}

for label, eval_model in [("pretrained", pretrained_model), ("finetuned", finetuned_longer_model)]:
    metrics = {'exact_matches': []}
    predictions = []
    for i, item in tqdm(enumerate(test_dataset)):
        question = item['question']
        answer = item['answer']
        try:
            predicted_answer = inference(question, eval_model, tokenizer)
        except:
            continue
        predictions.append([predicted_answer, answer])
        exact_match = is_exact_match(predicted_answer, answer)
        metrics['exact_matches'].append(exact_match)
        if i > n and n != -1:
            break
    results[label] = sum(metrics['exact_matches'])
    print(f"{label}: {sum(metrics['exact_matches'])} exact matches out of {len(metrics['exact_matches'])}")

print(results)

11it [00:12,  1.16s/it]

pretrained: 0 exact matches out of 12

11it [00:05,  1.97it/s]

finetuned: 0 exact matches out of 12
{'pretrained': 0, 'finetuned': 0}

In [274]:
df = pd.DataFrame(predictions, columns=["predicted_answer", "target_answer"])
print(df)

                                     predicted_answer  \
0   Yes, Lamini can generate technical documentati...
1   You can use the Authorization HTTP header to g...
2   Lamini’s LLM Engine is a LLM Engine for develo...
3   Yes, there is a community or support forum ava...
4   Yes, the Lamini library can be utilized for te...
5   Lamini is designed to be flexible and scalable...
6   You can instantiate the LLM engine using the L...
7   Yes, Lamini provides mechanisms for compressio...
8   The performance of LLMs trained using Lamini c...
9   Yes, there is a support and community availabl...
10  Yes, there are some code samples available in ...
11  Yes, there are some code samples available tha...

                                        target_answer
0   Yes, Lamini can generate technical documentati...
1   The Authorization HTTP header should include t...
2   Yes, the code includes a version parameter in ...
3   Yes, there is a community forum available for ...
4   The Lamini library is not specifically designe...
5   Lamini offers both free and paid plans for usi...
6   You can instantiate the LLM engine using the l...
7   Yes, Lamini provides mechanisms for model comp...
8   According to the information provided, Lamini ...
9   Yes, there is a support community available to...
10  Yes, the Python logging module documentation p...
11  Yes, there is a separate section in the docume...

In [275]:
#evaluate all data
evaluation_dataset_path = "lamini/lamini_docs_evaluation"
evaluation_dataset = datasets.load_dataset(evaluation_dataset_path)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2e19afc0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b2fc526f0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'271'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:43:31 GMT'), (b'Location', b'/api/resolve-cache/datasets/lamini/lamini_docs_evaluation/2978042a71b211bdc8ed88b3d13ed28f0554c790/README.md?%2Fdatasets%2Flamini%2Flamini_docs_evaluation%2Fresolve%2Fmain%2FREADME.md=&etag=%22865ba5a91a215c07442dcfa4a820810cab3883f4%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3f3-069d428b48be66dc491019ab;5daa867b-b990-4eec-a5b2-7529b53565f4'), (b'RateLimit', b'"resolvers";r=2961;t=217'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"865ba5a91a215c07442dcfa4a820810cab3883f4"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 e44b5448148b021c5ed201cf2434b6cc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'UJT3FkFk3tvV_bjCWczXxRrgp0Hlte1V1tZ5_Ak3Y98x6hzSQBLAsQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs_evaluation/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'413'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 03:39:16 GMT'), (b'ETag', b'"865ba5a91a215c07442dcfa4a820810cab3883f4"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76a4e4-61bcdcb34a9e7c9640607cc9;9603b12d-cace-4b31-8b91-eb26a8274fe9'), (b'RateLimit', b'"resolvers";r=2998;t=172'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'README.md; filename="README.md";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 e44b5448148b021c5ed201cf2434b6cc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'xyWE9XKMFZ9FORjOgsnWccroqtldcjoZ_Hcejpnj3p9x_yfebhUnyQ=='), (b'Age', b'3855')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/lamini/lamini_docs_evaluation/2978042a71b211bdc8ed88b3d13ed28f0554c790/README.md "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:43:31 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3f3-2c49e3e25e23f67e3409ec16;07915336-9435-4b54-964f-fafd6c5ea2a2'), (b'RateLimit', b'"resolvers";r=2960;t=217'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'Accept-Ranges', b'bytes'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e44b5448148b021c5ed201cf2434b6cc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'bmqlrW02qw6PEonL-8GE3y22iDdTjP03C7elA1moJVXBDVx_nrv2IA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs_evaluation/resolve/2978042a71b211bdc8ed88b3d13ed28f0554c790/lamini_docs_evaluation.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='s3.amazonaws.com' port=443 local_address=None timeout=3 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8abc8e00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='s3.amazonaws.com' timeout=3
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b64099520>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'x-amz-request-id', b'DVRXAASGZ948P0PR'), (b'x-amz-id-2', b'b1O4/6ZZpV/Mzm5L0yGEzHERpeaQ1k5hLDY6tnZczc2tYB5Qu1EUz+o44FXRednYnNsIVg5IyH4='), (b'Content-Type', b'application/xml'), (b'Transfer-Encoding', b'chunked'), (b'Date', b'Sat, 08 Aug 2026 04:43:31 GMT'), (b'Server', b'AmazonS3')])
INFO:httpx:HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/lamini/lamini_docs_evaluation/lamini/lamini_docs_evaluation.py "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:43:32 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3f3-4ba80b6a177787740ab3718e;68d20133-343a-4af5-997b-de87e5efc55f'), (b'RateLimit', b'"resolvers";r=2959;t=216'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e44b5448148b021c5ed201cf2434b6cc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'iBVveychKswb7sE7la31ZvoWjCExoW8G-d_1w1ZH655W3D5OP34TEQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs_evaluation/resolve/2978042a71b211bdc8ed88b3d13ed28f0554c790/.huggingface.yaml "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.connection:connect_tcp.started host='datasets-server.huggingface.co' port=443 local_address=None timeout=100.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b4fb369f0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='datasets-server.huggingface.co' timeout=100.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b4fb34200>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:43:32 GMT'), (b'vary', b'Accept-Encoding'), (b'content-encoding', b'gzip'), (b'server', b'uvicorn'), (b'cache-control', b'max-age=120'), (b'x-revision', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 ae84da1c4f982aa5b5a635f3473220ae.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P5'), (b'X-Amz-Cf-Id', b'JPWYx8FJEjvA6fhNyTadBmyfVru194IROjjo0XJDb4Qrn1QpWDsmjQ==')])
INFO:httpx:HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=lamini/lamini_docs_evaluation "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'15'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:43:32 GMT'), (b'ETag', b'W/"f-mY2VvLxuxB7KhsoOdQTlMTccuAQ"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b3f4-4cee343f40a4bbe65ab9a2d1;fffe1269-651f-4036-ae13-6ad116105927'), (b'RateLimit', b'"resolvers";r=2958;t=216'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'2978042a71b211bdc8ed88b3d13ed28f0554c790'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'Entry not found'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 e44b5448148b021c5ed201cf2434b6cc.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'SOEBMfLDPoRRZRupLMW5sOXbt5Su-GUuXZDmu8fHut9uPQfYFtjXrA==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/datasets/lamini/lamini_docs_evaluation/resolve/2978042a71b211bdc8ed88b3d13ed28f0554c790/dataset_infos.json "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs_evaluation/default/0.0.0/2978042a71b211bdc8ed88b3d13ed28f0554c790/dataset_info.json
DEBUG:fsspec.local:open file: /root/.cache/huggingface/datasets/lamini___lamini_docs_evaluation/default/0.0.0/2978042a71b211bdc8ed88b3d13ed28f0554c790/dataset_info.json

In [276]:
pd.DataFrame(evaluation_dataset)

                                                 train
0    {'predicted_answer': 'Yes, Lamini can generate...
1    {'predicted_answer': 'You can use the Authoriz...
2    {'predicted_answer': 'Lamini’s LLM Engine is a...
3    {'predicted_answer': 'Yes, there is a communit...
4    {'predicted_answer': 'Yes, the Lamini library ...
..                                                 ...
134  {'predicted_answer': 'Yes, Lamini has the abil...
135  {'predicted_answer': 'I wish! This documentati...
136  {'predicted_answer': 'Yes, Lamini can generate...
137  {'predicted_answer': 'Yes, the documentation h...
138  {'predicted_answer': 'Yes, you can learn to us...

[139 rows x 1 columns]

In [277]:
#arc benchmark
!pip install -q "lm_eval[hf]"

In [278]:
import os

print(os.listdir("/content"))

['.config', 'lamini_docs_processed.jsonl', 'utilities.py', 'lamini_docs.jsonl', 'lamini_docs_3_steps', 'llama.py', 'alpaca_processed.jsonl', '__pycache__', 'sample_data']

In [279]:
print(output_dir)

lamini_docs_3_steps

In [280]:
import os

print(os.listdir("/content/lamini_docs_3_steps"))

['checkpoint-3', 'final']

In [281]:
import os

print(os.listdir("/content/lamini_docs_3_steps/final"))

['tokenizer_config.json', 'training_args.bin', 'config.json', 'tokenizer.json', 'model.safetensors', 'generation_config.json']

In [283]:
from transformers import AutoTokenizer

path = "/content/lamini_docs_3_steps/final"

tokenizer = AutoTokenizer.from_pretrained(path)

print("Tokenizer:", tokenizer)
print("Vocab size:", tokenizer.vocab_size)
print("EOS:", tokenizer.eos_token, tokenizer.eos_token_id)
print("BOS:", tokenizer.bos_token, tokenizer.bos_token_id)
print("PAD:", tokenizer.pad_token, tokenizer.pad_token_id)

text = "Question: What is the capital of France?\nAnswer:"

tokens = tokenizer.encode(text, add_special_tokens=True)

print("Tokens:", tokens)
print("Number of tokens:", len(tokens))

Tokenizer: GPTNeoXTokenizer(name_or_path='/content/lamini_docs_3_steps/final', vocab_size=50254, model_max_length=1000000000000000019884624838656, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<|padding|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50254: AddedToken("                        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50255: AddedToken("                       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50256: AddedToken("                      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50257: AddedToken("                     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50258: AddedToken("                    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50259: AddedToken("                   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50260: AddedToken("                  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50261: AddedToken("                 ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50262: AddedToken("                ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50263: AddedToken("               ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50264: AddedToken("              ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50265: AddedToken("             ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("            ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("           ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("          ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50269: AddedToken("         ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50270: AddedToken("        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50271: AddedToken("       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50272: AddedToken("      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50273: AddedToken("     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50274: AddedToken("    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50275: AddedToken("   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50276: AddedToken("  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
})
Vocab size: 50254
EOS: <|endoftext|> 0
BOS: <|endoftext|> 0
PAD: <|endoftext|> 0
Tokens: [23433, 27, 1737, 310, 253, 5347, 273, 6181, 32, 187, 32869, 27]
Number of tokens: 12

In [284]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-410m")

print("Vocab size:", tokenizer.vocab_size)

DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
DEBUG:httpcore.connection:connect_tcp.started host='huggingface.co' port=443 local_address=None timeout=10 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b8e150e00>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x783ccaa7fe50> server_hostname='huggingface.co' timeout=10
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x783b495c7b00>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'248'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:45:26 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-410m/9879c9b5f8bea9051dcb0e68dff21493d67e9d4f/config.json?%2FEleutherAI%2Fpythia-410m%2Fresolve%2Fmain%2Fconfig.json=&etag=%220425fa136ba3f95d9428d832cfd7bfd82c78bf1f%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b466-208666714953b8df4a94032a;064e64c3-fee7-44d5-a514-51fa7a5f2aa1'), (b'RateLimit', b'"resolvers";r=2953;t=102'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'9879c9b5f8bea9051dcb0e68dff21493d67e9d4f'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"0425fa136ba3f95d9428d832cfd7bfd82c78bf1f"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BI8hpAxzr9A_CicuIhKVPUMSHR3IpYz4olX5F5Bm9QrQxmU2dljUcQ==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-410m/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'570'), (b'Connection', b'keep-alive'), (b'Date', b'Thu, 28 Aug 2025 19:54:06 GMT'), (b'ETag', b'"0425fa136ba3f95d9428d832cfd7bfd82c78bf1f"'), (b'X-Powered-By', b'huggingface-moon'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'X-Request-Id', b'Root=1-68b0b3de-7b05c21e0026ac69126de011;81929348-b96b-4ff2-9a56-e93f62cfaf34'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'9879c9b5f8bea9051dcb0e68dff21493d67e9d4f'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'config.json; filename="config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'd9mnTW_c-zrzdPo7xZ6gll1Cw05lV1jyjXY95XJq7WvaD0pEa16DmA=='), (b'Age', b'29753480')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-410m/9879c9b5f8bea9051dcb0e68dff21493d67e9d4f/config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 307, b'Temporary Redirect', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'268'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:45:26 GMT'), (b'Location', b'/api/resolve-cache/models/EleutherAI/pythia-410m/9879c9b5f8bea9051dcb0e68dff21493d67e9d4f/tokenizer_config.json?%2FEleutherAI%2Fpythia-410m%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22f1860edb10f80bcaf7b023fce47c68a23b724c23%22'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b466-2a9b781c18d06c3f10987f07;c139eda7-5dc6-4e0f-9a66-27de409335d5'), (b'RateLimit', b'"resolvers";r=2952;t=102'), (b'RateLimit-Policy', b'"fixed window";"resolvers";q=3000;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin, Accept'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'9879c9b5f8bea9051dcb0e68dff21493d67e9d4f'), (b'Accept-Ranges', b'bytes'), (b'X-HF-Warning', b'unauthenticated; Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.'), (b'X-Hub-Cache', b'MISS'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'X-Linked-ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'BFBic_BiGWvVAQ6Ew3QoZfn7pz-HEOy-TR0IsQsJoD1Lv6_Uy8Q3-Q==')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/EleutherAI/pythia-410m/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'text/plain; charset=utf-8'), (b'Content-Length', b'396'), (b'Connection', b'keep-alive'), (b'Date', b'Thu, 28 Aug 2025 19:54:19 GMT'), (b'ETag', b'"f1860edb10f80bcaf7b023fce47c68a23b724c23"'), (b'X-Powered-By', b'huggingface-moon'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'X-Request-Id', b'Root=1-68b0b3eb-3a6bf3d054e9f6e312b1c034;8dc94e15-271e-46a4-9873-c4c125226e2d'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Repo-Commit', b'9879c9b5f8bea9051dcb0e68dff21493d67e9d4f'), (b'Accept-Ranges', b'bytes'), (b'Content-Disposition', b'inline; filename*=UTF-8\'\'tokenizer_config.json; filename="tokenizer_config.json";'), (b'Content-Security-Policy', b"default-src 'none'; sandbox"), (b'Vary', b'Origin'), (b'X-Cache', b'Hit from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'll7C7SmfshHjYWP6V505HRZ4LU9EDCrbOUGo0I48z8JP6pb0JCZD7A=='), (b'Age', b'29753467')])
INFO:httpx:HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/EleutherAI/pythia-410m/9879c9b5f8bea9051dcb0e68dff21493d67e9d4f/tokenizer_config.json "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'HEAD']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 404, b'Not Found', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'64'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:45:26 GMT'), (b'ETag', b'W/"40-09f9IAqP13xarAhQxFS2W8rvRkM"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b466-1409acdf61bcfe2d3ad9245a;385948e4-644a-417f-b1e2-2290e19c7071'), (b'RateLimit', b'"api";r=487;t=102'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Error-Code', b'EntryNotFound'), (b'X-Error-Message', b'additional_chat_templates does not exist on "main"'), (b'X-Cache', b'Error from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'EqQJEqBiVyUBCtsectR5BFETJdJoHJvbFmaVOdnZyjYRNJxOxwNxBw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-410m/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Content-Type', b'application/json; charset=utf-8'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'Date', b'Sat, 08 Aug 2026 04:45:26 GMT'), (b'content-encoding', b'gzip'), (b'ETag', b'W/"4c3-sm3yTU6GO64atRYUDEGtWat4oR4"'), (b'X-Powered-By', b'huggingface-moon'), (b'X-Request-Id', b'Root=1-6a76b466-20b5d8b737d09ec748e2291b;7dc5711b-4813-4361-87c6-7c2c97bbbdef'), (b'RateLimit', b'"api";r=486;t=102'), (b'RateLimit-Policy', b'"fixed window";"api";q=500;w=300'), (b'cross-origin-opener-policy', b'same-origin'), (b'Referrer-Policy', b'strict-origin-when-cross-origin'), (b'Access-Control-Max-Age', b'86400'), (b'Access-Control-Allow-Origin', b'https://huggingface.co'), (b'Vary', b'Origin'), (b'vary', b'Accept-Encoding'), (b'Access-Control-Expose-Headers', b'X-Repo-Commit,X-Request-Id,X-Error-Code,X-Error-Message,X-Total-Count,ETag,Link,Accept-Ranges,Content-Range,X-Linked-Size,X-Linked-ETag,X-Xet-Hash'), (b'X-Cache', b'Miss from cloudfront'), (b'Via', b'1.1 dc1a987d649e26c30b46018807322438.cloudfront.net (CloudFront)'), (b'X-Amz-Cf-Pop', b'LAX53-P4'), (b'Alt-Svc', b'h3=":443"; ma=86400'), (b'X-Amz-Cf-Id', b'sVdaXq5wU9cAmI4Ws_QAChvXa9IK-wKSeH23opXrAMhHl5HvTyQBpw==')])
INFO:httpx:HTTP Request: GET https://huggingface.co/api/models/EleutherAI/pythia-410m/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete

Vocab size: 50254

In [285]:
print("Vocab size:", tokenizer.vocab_size)

Vocab size: 50254

In [286]:
tokenizer.pad_token = tokenizer.eos_token

In [287]:
tokenizer.save_pretrained("/content/lamini_docs_3_steps/final")

('/content/lamini_docs_3_steps/final/tokenizer_config.json',
 '/content/lamini_docs_3_steps/final/tokenizer.json')

In [288]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "/content/lamini_docs_3_steps/final"
)

print("Vocab size:", tokenizer.vocab_size)

text = "Question: What is the capital of France?\nAnswer:"
tokens = tokenizer.encode(text, add_special_tokens=True)

print("Tokens:", tokens)
print("Number of tokens:", len(tokens))

Vocab size: 50254
Tokens: [23433, 27, 1737, 310, 253, 5347, 273, 6181, 32, 187, 32869, 27]
Number of tokens: 12

In [289]:
tokenizer.pad_token = tokenizer.eos_token

tokenizer.save_pretrained(
    "/content/lamini_docs_3_steps/final"
)

('/content/lamini_docs_3_steps/final/tokenizer_config.json',
 '/content/lamini_docs_3_steps/final/tokenizer.json')

In [290]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "/content/lamini_docs_3_steps/final"
)

print("Vocab size:", tokenizer.vocab_size)

tokens = tokenizer.encode(
    "Question: What is the capital of France?\nAnswer:",
    add_special_tokens=True
)

print("Number of tokens:", len(tokens))

Vocab size: 50254
Number of tokens: 12

In [293]:
from transformers import AutoConfig

final_path = "/content/lamini_docs_3_steps/final"

config = AutoConfig.from_pretrained(final_path)

print("Model type:", config.model_type)
print("Hidden size:", config.hidden_size)
print("Number of layers:", config.num_hidden_layers)
print("Number of attention heads:", config.num_attention_heads)
print("Vocabulary size:", config.vocab_size)

Model type: gpt_neox
Hidden size: 512
Number of layers: 6
Number of attention heads: 8
Vocabulary size: 50304

In [299]:
!lm-eval run \
    --model hf \
    --model_args pretrained=EleutherAI/pythia-70m \
    --tasks arc_easy \
    --device cuda:0 \
    --batch_size 1 \
    --output_path /content/results_pretrained/

2026-08-08:05:16:45 INFO     [_cli.run:388] Selected Tasks: ['arc_easy']
2026-08-08:05:16:47 INFO     [evaluator:214] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234
2026-08-08:05:16:47 INFO     [evaluator:239] Initializing hf model, with arguments: {'pretrained': 'EleutherAI/pythia-70m'}
2026-08-08:05:16:52 INFO     [models.huggingface:286] Using device 'cuda:0'
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-08:05:16:53 INFO     [models.huggingface:579] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cuda:0'}
Loading weights: 100% 76/76 [00:00<00:00, 1696.32it/s]
2026-08-08:05:16:55 INFO     [evaluator_utils:446] Selected tasks:
2026-08-08:05:16:55 INFO     [evaluator_utils:480] Task: arc_easy (arc/arc_easy.yaml)
2026-08-08:05:16:55 INFO     [api.task:312] Building contexts for arc_easy on rank 0...
100% 2376/2376 [00:08<00:00, 276.44it/s]
2026-08-08:05:17:04 INFO     [evaluator:585] Running loglikelihood requests
Tokenizing inputs: 100% 9501/9501 [00:02<00:00, 4230.96it/s]
Running loglikelihood requests: 100% 9501/9501 [00:56<00:00, 166.82it/s]
fatal: not a git repository (or any of the parent directories): .git
2026-08-08:05:18:09 INFO     [loggers.evaluation_tracker:247] Saving results aggregated
hf ({'pretrained': 'EleutherAI/pythia-70m'}), gen_kwargs: ({}), limit: None, num_fewshot: None, batch_size: 1
| Tasks  |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|--------|------:|------|-----:|--------|---|-----:|---|-----:|
|arc_easy|      1|none  |     0|acc     |↑  |0.3670|±  |0.0099|
|        |       |none  |     0|acc_norm|↑  |0.3506|±  |0.0098|

In [300]:
!lm-eval run \
    --model hf \
    --model_args pretrained=lamini/lamini_docs_finetuned \
    --tasks arc_easy \
    --device cuda:0 \
    --batch_size 1 \
    --output_path /content/results_finetuned/

2026-08-08:05:18:57 INFO     [_cli.run:388] Selected Tasks: ['arc_easy']
2026-08-08:05:19:00 INFO     [evaluator:214] Setting random seed to 0 | Setting numpy seed to 1234 | Setting torch manual seed to 1234 | Setting fewshot manual seed to 1234
2026-08-08:05:19:00 INFO     [evaluator:239] Initializing hf model, with arguments: {'pretrained': 'lamini/lamini_docs_finetuned'}
2026-08-08:05:19:08 INFO     [models.huggingface:286] Using device 'cuda:0'
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-08:05:19:09 INFO     [models.huggingface:579] Model parallel was set to False, max memory was not set, and device map was set to {'': 'cuda:0'}
Loading weights: 100% 76/76 [00:00<00:00, 1055.91it/s]
2026-08-08:05:19:11 INFO     [evaluator_utils:446] Selected tasks:
2026-08-08:05:19:11 INFO     [evaluator_utils:480] Task: arc_easy (arc/arc_easy.yaml)
2026-08-08:05:19:11 INFO     [api.task:312] Building contexts for arc_easy on rank 0...
100% 2376/2376 [00:06<00:00, 370.20it/s]
2026-08-08:05:19:18 INFO     [evaluator:585] Running loglikelihood requests
Tokenizing inputs:   0% 0/9501 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPTNeoXTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
Tokenizing inputs: 100% 9501/9501 [00:05<00:00, 1821.98it/s]
Running loglikelihood requests: 100% 9501/9501 [00:55<00:00, 170.58it/s]
fatal: not a git repository (or any of the parent directories): .git
2026-08-08:05:20:25 INFO     [loggers.evaluation_tracker:247] Saving results aggregated
hf ({'pretrained': 'lamini/lamini_docs_finetuned'}), gen_kwargs: ({}), limit: None, num_fewshot: None, batch_size: 1
| Tasks  |Version|Filter|n-shot| Metric |   |Value |   |Stderr|
|--------|------:|------|-----:|--------|---|-----:|---|-----:|
|arc_easy|      1|none  |     0|acc     |↑  |0.3123|±  |0.0095|
|        |       |none  |     0|acc_norm|↑  |0.3136|±  |0.0095|

In [301]:
import json, glob

def load_acc(path_glob):
    f = glob.glob(path_glob)[0]
    with open(f) as fh:
        data = json.load(fh)
    return data["results"]["arc_easy"]["acc,none"]

acc_pretrained = load_acc("/content/results_pretrained/**/*.json")
acc_finetuned = load_acc("/content/results_finetuned/**/*.json")

print("Pretrained acc:", acc_pretrained)
print("Finetuned acc:", acc_finetuned)

Pretrained acc: 0.367003367003367
Finetuned acc: 0.3122895622895623